import { Link } from "react-router-dom";
import { useEffect, useRef } from "react";
import Layout from "./Layout";
import ProfileMenu from "@/components/ProfileMenu";
import { useAuth } from "@/hooks/useAuth";
import { useTrainingPlan } from "@/hooks/useTrainingPlan";

export default function HomePage() {
  const { user, player } = useAuth();
  const { data: planData, generatePlan } = useTrainingPlan(
    player?.id ?? undefined
  );
  const hasAutoGenerated = useRef(false);

  // Auto-generate a training plan if the player doesn't have one
  useEffect(() => {
    if (
      player &&
      planData === null &&
      !generatePlan.isPending &&
      !hasAutoGenerated.current
    ) {
      hasAutoGenerated.current = true;
      generatePlan.mutate({
        playerId: player.id,
        category: player.category,
      });
    }
  }, [player, planData, generatePlan]);

  const btnClass =
    "flex-1 bg-accent-red hover:bg-accent-red-dark text-white font-semibold py-4 px-6 rounded-2xl transition-all duration-200 transform hover:scale-[1.02] hover:shadow-glow-red active:scale-[0.98] shadow-lg flex items-center justify-center text-base";

  const btnDisabledClass =
    "flex-1 bg-gray-700 text-gray-400 font-semibold py-4 px-6 rounded-2xl shadow-lg flex items-center justify-center text-base cursor-not-allowed";

  return (
    <Layout>
      <div className="relative min-h-[90vh] flex flex-col px-4 py-4">
        {/* Top Right User Menu */}
        <div className="absolute right-4 z-10">
          <ProfileMenu />
        </div>

        <div className="flex-1 flex flex-col items-center justify-center text-center">
          {/* Main Card */}
          <div className="w-full max-w-lg bg-dark-card rounded-3xl shadow-card p-8 border border-dark-border">
            <div className="mb-8">
              <img
                src="/ball.png"
                alt="Pool Valencia Logo"
                className="w-48 mx-auto mb-6 rounded-2xl"
              />
              <h1 className="text-3xl md:text-4xl font-bold text-white mb-2 leading-tight">
                Ranking PoolValencia
              </h1>
            </div>

            <div className="flex flex-col gap-3">
              {/* Personal section - only when logged in and linked */}
              {player && (
                <>
                  <div className="text-gray-400 text-sm text-left">
                    {player.name}
                  </div>
                  <div className="flex gap-3 w-full">
                    <Link to={`/players/${player.id}`} className={btnClass}>
                      Mi perfil
                    </Link>
                    <Link
                      to={`/entrenamientos/plan/${player.id}`}
                      className={btnClass}
                    >
                      Mi entrenamiento
                    </Link>
                  </div>
                </>
              )}

              <div className="text-gray-400 text-sm text-left">Rankings</div>
              <div className="flex gap-3 w-full">
                <Link to="/ranking-diario" className={btnClass}>
                  Diario
                </Link>
                <Link to="/ranking" className={btnClass}>
                  Global
                </Link>
              </div>
              <div className="text-gray-400 text-sm text-left">Partidos</div>
              <div className="flex gap-3 w-full">
                <Link to="/partidos" className={btnClass}>
                  Todos los partidos
                </Link>
                <Link to="/añadir-partido" className={btnClass}>
                  Añadir partido
                </Link>
              </div>
              <div className="text-gray-400 text-sm text-left">Jugadores</div>
              <Link to="/players" className={btnClass}>
                Todos los jugadores
              </Link>
              <div className="text-gray-400 text-sm text-left">
                Entrenamientos
              </div>
              {user ? (
                <div className="flex gap-3 w-full">
                  <Link to="/entrenamientos" className={btnClass}>
                    Ejercicios
                  </Link>
                  {player ? (
                    <Link
                      to={`/entrenamientos/progreso/${player.id}`}
                      className={btnClass}
                    >
                      Mi progreso
                    </Link>
                  ) : (
                    <Link to="/entrenamientos" className={btnClass}>
                      Plan automático
                    </Link>
                  )}
                </div>
              ) : (
                <div className="flex gap-3 w-full">
                  <span className={btnDisabledClass}>Ejercicios</span>
                  <span className={btnDisabledClass}>Plan automático</span>
                </div>
              )}
              {!user && (
                <p className="text-xs text-gray-500">
                  Inicia sesión para acceder a los entrenamientos
                </p>
              )}
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}
