/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as AppAuthedRouteRouteImport } from './routes/app/_authed/route'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as PublicClubsIndexRouteImport } from './routes/_public/clubs/index'
import { Route as PublicClubsSlugRouteImport } from './routes/_public/clubs/$slug'
import { Route as PublicDrillsIndexRouteImport } from './routes/_public/drills/index'
import { Route as PublicDrillsDrillIdRouteImport } from './routes/_public/drills/$drillId'
import { Route as PublicPlayersIndexRouteImport } from './routes/_public/players/index'
import { Route as PublicPlayersPlayerSlugRouteImport } from './routes/_public/players/$playerSlug'
import { Route as PublicTournamentsIndexRouteImport } from './routes/_public/tournaments/index'
import { Route as PublicTournamentsTournamentIdRouteImport } from './routes/_public/tournaments/$tournamentId'
import { Route as AppAuthedIndexRouteImport } from './routes/app/_authed/index'
import { Route as AppAuthedClubSlugRouteRouteImport } from './routes/app/_authed/$clubSlug/route'
import { Route as AppJoinCodeRouteImport } from './routes/app/join.$code'
import { Route as AppAuthedClubSlugIndexRouteImport } from './routes/app/_authed/$clubSlug/index'
import { Route as AppAuthedClubSlugChallengesRouteImport } from './routes/app/_authed/$clubSlug/challenges'
import { Route as AppAuthedClubSlugClubRouteImport } from './routes/app/_authed/$clubSlug/club'
import { Route as AppAuthedClubsNewRouteImport } from './routes/app/_authed/clubs.new'
import { Route as AppAuthedClubSlugDrillsIndexRouteImport } from './routes/app/_authed/$clubSlug/drills/index'
import { Route as AppAuthedClubSlugDrillsNewRouteImport } from './routes/app/_authed/$clubSlug/drills/new'
import { Route as AppAuthedClubSlugGamesIndexRouteImport } from './routes/app/_authed/$clubSlug/games/index'
import { Route as AppAuthedClubSlugGamesNewRouteImport } from './routes/app/_authed/$clubSlug/games/new'
import { Route as AppAuthedClubSlugMeIndexRouteImport } from './routes/app/_authed/$clubSlug/me/index'
import { Route as AppAuthedClubSlugMeSettingsRouteImport } from './routes/app/_authed/$clubSlug/me/settings'
import { Route as AppAuthedClubSlugPlayersIndexRouteImport } from './routes/app/_authed/$clubSlug/players/index'
import { Route as AppAuthedClubSlugRankingIndexRouteImport } from './routes/app/_authed/$clubSlug/ranking/index'
import { Route as AppAuthedClubSlugRankingDailyRouteImport } from './routes/app/_authed/$clubSlug/ranking/daily'
import { Route as AppAuthedClubSlugTournamentsIndexRouteImport } from './routes/app/_authed/$clubSlug/tournaments/index'
import { Route as AppAuthedClubSlugTournamentsTournamentIdRouteImport } from './routes/app/_authed/$clubSlug/tournaments/$tournamentId'
import { Route as AppAuthedClubSlugDrillsDrillIdIndexRouteImport } from './routes/app/_authed/$clubSlug/drills/$drillId/index'
import { Route as AppAuthedClubSlugDrillsDrillIdEditRouteImport } from './routes/app/_authed/$clubSlug/drills/$drillId/edit'
import { Route as AppAuthedClubSlugMeTrainingIndexRouteImport } from './routes/app/_authed/$clubSlug/me/training/index'
import { Route as AppAuthedClubSlugMeTrainingPlanRouteImport } from './routes/app/_authed/$clubSlug/me/training/plan'
import { Route as AppAuthedClubSlugPlayersPlayerIdIndexRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/index'
import { Route as AppAuthedClubSlugPlayersPlayerIdSettingsRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/settings'
import { Route as AppAuthedClubSlugPlayersPlayerIdTrainingIndexRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/training/index'
import { Route as AppAuthedClubSlugPlayersPlayerIdTrainingPlanRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/training/plan'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppAuthedRouteRoute = AppAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicClubsIndexRoute = PublicClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicClubsSlugRoute = PublicClubsSlugRouteImport.update({
  id: '/clubs/$slug',
  path: '/clubs/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDrillsIndexRoute = PublicDrillsIndexRouteImport.update({
  id: '/drills/',
  path: '/drills/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDrillsDrillIdRoute = PublicDrillsDrillIdRouteImport.update({
  id: '/drills/$drillId',
  path: '/drills/$drillId',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPlayersIndexRoute = PublicPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPlayersPlayerSlugRoute = PublicPlayersPlayerSlugRouteImport.update({
  id: '/players/$playerSlug',
  path: '/players/$playerSlug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTournamentsIndexRoute = PublicTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTournamentsTournamentIdRoute =
  PublicTournamentsTournamentIdRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedClubSlugRouteRoute = AppAuthedClubSlugRouteRouteImport.update({
  id: '/$clubSlug',
  path: '/$clubSlug',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppJoinCodeRoute = AppJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthedClubSlugIndexRoute = AppAuthedClubSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedClubSlugRouteRoute,
} as any)
const AppAuthedClubSlugChallengesRoute =
  AppAuthedClubSlugChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugClubRoute = AppAuthedClubSlugClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => AppAuthedClubSlugRouteRoute,
} as any)
const AppAuthedClubsNewRoute = AppAuthedClubsNewRouteImport.update({
  id: '/clubs/new',
  path: '/clubs/new',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedClubSlugDrillsIndexRoute =
  AppAuthedClubSlugDrillsIndexRouteImport.update({
    id: '/drills/',
    path: '/drills/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugDrillsNewRoute =
  AppAuthedClubSlugDrillsNewRouteImport.update({
    id: '/drills/new',
    path: '/drills/new',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugGamesIndexRoute =
  AppAuthedClubSlugGamesIndexRouteImport.update({
    id: '/games/',
    path: '/games/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugGamesNewRoute =
  AppAuthedClubSlugGamesNewRouteImport.update({
    id: '/games/new',
    path: '/games/new',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeIndexRoute =
  AppAuthedClubSlugMeIndexRouteImport.update({
    id: '/me/',
    path: '/me/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeSettingsRoute =
  AppAuthedClubSlugMeSettingsRouteImport.update({
    id: '/me/settings',
    path: '/me/settings',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersIndexRoute =
  AppAuthedClubSlugPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugRankingIndexRoute =
  AppAuthedClubSlugRankingIndexRouteImport.update({
    id: '/ranking/',
    path: '/ranking/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugRankingDailyRoute =
  AppAuthedClubSlugRankingDailyRouteImport.update({
    id: '/ranking/daily',
    path: '/ranking/daily',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugTournamentsIndexRoute =
  AppAuthedClubSlugTournamentsIndexRouteImport.update({
    id: '/tournaments/',
    path: '/tournaments/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugTournamentsTournamentIdRoute =
  AppAuthedClubSlugTournamentsTournamentIdRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugDrillsDrillIdIndexRoute =
  AppAuthedClubSlugDrillsDrillIdIndexRouteImport.update({
    id: '/drills/$drillId/',
    path: '/drills/$drillId/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugDrillsDrillIdEditRoute =
  AppAuthedClubSlugDrillsDrillIdEditRouteImport.update({
    id: '/drills/$drillId/edit',
    path: '/drills/$drillId/edit',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeTrainingIndexRoute =
  AppAuthedClubSlugMeTrainingIndexRouteImport.update({
    id: '/me/training/',
    path: '/me/training/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeTrainingPlanRoute =
  AppAuthedClubSlugMeTrainingPlanRouteImport.update({
    id: '/me/training/plan',
    path: '/me/training/plan',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdIndexRoute =
  AppAuthedClubSlugPlayersPlayerIdIndexRouteImport.update({
    id: '/players/$playerId/',
    path: '/players/$playerId/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdSettingsRoute =
  AppAuthedClubSlugPlayersPlayerIdSettingsRouteImport.update({
    id: '/players/$playerId/settings',
    path: '/players/$playerId/settings',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute =
  AppAuthedClubSlugPlayersPlayerIdTrainingIndexRouteImport.update({
    id: '/players/$playerId/training/',
    path: '/players/$playerId/training/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute =
  AppAuthedClubSlugPlayersPlayerIdTrainingPlanRouteImport.update({
    id: '/players/$playerId/training/plan',
    path: '/players/$playerId/training/plan',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/search': typeof PublicSearchRoute
  '/app/login': typeof AppLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/$clubSlug': typeof AppAuthedClubSlugRouteRouteWithChildren
  '/clubs/$slug': typeof PublicClubsSlugRoute
  '/drills/$drillId': typeof PublicDrillsDrillIdRoute
  '/players/$playerSlug': typeof PublicPlayersPlayerSlugRoute
  '/tournaments/$tournamentId': typeof PublicTournamentsTournamentIdRoute
  '/app/join/$code': typeof AppJoinCodeRoute
  '/clubs/': typeof PublicClubsIndexRoute
  '/drills/': typeof PublicDrillsIndexRoute
  '/players/': typeof PublicPlayersIndexRoute
  '/tournaments/': typeof PublicTournamentsIndexRoute
  '/app/': typeof AppAuthedIndexRoute
  '/app/$clubSlug/challenges': typeof AppAuthedClubSlugChallengesRoute
  '/app/$clubSlug/club': typeof AppAuthedClubSlugClubRoute
  '/app/clubs/new': typeof AppAuthedClubsNewRoute
  '/app/$clubSlug/': typeof AppAuthedClubSlugIndexRoute
  '/app/$clubSlug/drills/new': typeof AppAuthedClubSlugDrillsNewRoute
  '/app/$clubSlug/games/new': typeof AppAuthedClubSlugGamesNewRoute
  '/app/$clubSlug/me/settings': typeof AppAuthedClubSlugMeSettingsRoute
  '/app/$clubSlug/ranking/daily': typeof AppAuthedClubSlugRankingDailyRoute
  '/app/$clubSlug/tournaments/$tournamentId': typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  '/app/$clubSlug/drills/': typeof AppAuthedClubSlugDrillsIndexRoute
  '/app/$clubSlug/games/': typeof AppAuthedClubSlugGamesIndexRoute
  '/app/$clubSlug/me/': typeof AppAuthedClubSlugMeIndexRoute
  '/app/$clubSlug/players/': typeof AppAuthedClubSlugPlayersIndexRoute
  '/app/$clubSlug/ranking/': typeof AppAuthedClubSlugRankingIndexRoute
  '/app/$clubSlug/tournaments/': typeof AppAuthedClubSlugTournamentsIndexRoute
  '/app/$clubSlug/drills/$drillId/edit': typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  '/app/$clubSlug/me/training/plan': typeof AppAuthedClubSlugMeTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/settings': typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  '/app/$clubSlug/drills/$drillId/': typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  '/app/$clubSlug/me/training/': typeof AppAuthedClubSlugMeTrainingIndexRoute
  '/app/$clubSlug/players/$playerId/': typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  '/app/$clubSlug/players/$playerId/training/plan': typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/training/': typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppAuthedIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/search': typeof PublicSearchRoute
  '/app/login': typeof AppLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof PublicIndexRoute
  '/clubs/$slug': typeof PublicClubsSlugRoute
  '/drills/$drillId': typeof PublicDrillsDrillIdRoute
  '/players/$playerSlug': typeof PublicPlayersPlayerSlugRoute
  '/tournaments/$tournamentId': typeof PublicTournamentsTournamentIdRoute
  '/app/join/$code': typeof AppJoinCodeRoute
  '/clubs': typeof PublicClubsIndexRoute
  '/drills': typeof PublicDrillsIndexRoute
  '/players': typeof PublicPlayersIndexRoute
  '/tournaments': typeof PublicTournamentsIndexRoute
  '/app/$clubSlug/challenges': typeof AppAuthedClubSlugChallengesRoute
  '/app/$clubSlug/club': typeof AppAuthedClubSlugClubRoute
  '/app/clubs/new': typeof AppAuthedClubsNewRoute
  '/app/$clubSlug': typeof AppAuthedClubSlugIndexRoute
  '/app/$clubSlug/drills/new': typeof AppAuthedClubSlugDrillsNewRoute
  '/app/$clubSlug/games/new': typeof AppAuthedClubSlugGamesNewRoute
  '/app/$clubSlug/me/settings': typeof AppAuthedClubSlugMeSettingsRoute
  '/app/$clubSlug/ranking/daily': typeof AppAuthedClubSlugRankingDailyRoute
  '/app/$clubSlug/tournaments/$tournamentId': typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  '/app/$clubSlug/drills': typeof AppAuthedClubSlugDrillsIndexRoute
  '/app/$clubSlug/games': typeof AppAuthedClubSlugGamesIndexRoute
  '/app/$clubSlug/me': typeof AppAuthedClubSlugMeIndexRoute
  '/app/$clubSlug/players': typeof AppAuthedClubSlugPlayersIndexRoute
  '/app/$clubSlug/ranking': typeof AppAuthedClubSlugRankingIndexRoute
  '/app/$clubSlug/tournaments': typeof AppAuthedClubSlugTournamentsIndexRoute
  '/app/$clubSlug/drills/$drillId/edit': typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  '/app/$clubSlug/me/training/plan': typeof AppAuthedClubSlugMeTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/settings': typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  '/app/$clubSlug/drills/$drillId': typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  '/app/$clubSlug/me/training': typeof AppAuthedClubSlugMeTrainingIndexRoute
  '/app/$clubSlug/players/$playerId': typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  '/app/$clubSlug/players/$playerId/training/plan': typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/training': typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/_authed': typeof AppAuthedRouteRouteWithChildren
  '/_public/search': typeof PublicSearchRoute
  '/app/login': typeof AppLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_public/': typeof PublicIndexRoute
  '/app/_authed/$clubSlug': typeof AppAuthedClubSlugRouteRouteWithChildren
  '/_public/clubs/$slug': typeof PublicClubsSlugRoute
  '/_public/drills/$drillId': typeof PublicDrillsDrillIdRoute
  '/_public/players/$playerSlug': typeof PublicPlayersPlayerSlugRoute
  '/_public/tournaments/$tournamentId': typeof PublicTournamentsTournamentIdRoute
  '/app/join/$code': typeof AppJoinCodeRoute
  '/_public/clubs/': typeof PublicClubsIndexRoute
  '/_public/drills/': typeof PublicDrillsIndexRoute
  '/_public/players/': typeof PublicPlayersIndexRoute
  '/_public/tournaments/': typeof PublicTournamentsIndexRoute
  '/app/_authed/': typeof AppAuthedIndexRoute
  '/app/_authed/$clubSlug/challenges': typeof AppAuthedClubSlugChallengesRoute
  '/app/_authed/$clubSlug/club': typeof AppAuthedClubSlugClubRoute
  '/app/_authed/clubs/new': typeof AppAuthedClubsNewRoute
  '/app/_authed/$clubSlug/': typeof AppAuthedClubSlugIndexRoute
  '/app/_authed/$clubSlug/drills/new': typeof AppAuthedClubSlugDrillsNewRoute
  '/app/_authed/$clubSlug/games/new': typeof AppAuthedClubSlugGamesNewRoute
  '/app/_authed/$clubSlug/me/settings': typeof AppAuthedClubSlugMeSettingsRoute
  '/app/_authed/$clubSlug/ranking/daily': typeof AppAuthedClubSlugRankingDailyRoute
  '/app/_authed/$clubSlug/tournaments/$tournamentId': typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  '/app/_authed/$clubSlug/drills/': typeof AppAuthedClubSlugDrillsIndexRoute
  '/app/_authed/$clubSlug/games/': typeof AppAuthedClubSlugGamesIndexRoute
  '/app/_authed/$clubSlug/me/': typeof AppAuthedClubSlugMeIndexRoute
  '/app/_authed/$clubSlug/players/': typeof AppAuthedClubSlugPlayersIndexRoute
  '/app/_authed/$clubSlug/ranking/': typeof AppAuthedClubSlugRankingIndexRoute
  '/app/_authed/$clubSlug/tournaments/': typeof AppAuthedClubSlugTournamentsIndexRoute
  '/app/_authed/$clubSlug/drills/$drillId/edit': typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  '/app/_authed/$clubSlug/me/training/plan': typeof AppAuthedClubSlugMeTrainingPlanRoute
  '/app/_authed/$clubSlug/players/$playerId/settings': typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  '/app/_authed/$clubSlug/drills/$drillId/': typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  '/app/_authed/$clubSlug/me/training/': typeof AppAuthedClubSlugMeTrainingIndexRoute
  '/app/_authed/$clubSlug/players/$playerId/': typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  '/app/_authed/$clubSlug/players/$playerId/training/plan': typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  '/app/_authed/$clubSlug/players/$playerId/training/': typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/search'
    | '/app/login'
    | '/auth/callback'
    | '/app/$clubSlug'
    | '/clubs/$slug'
    | '/drills/$drillId'
    | '/players/$playerSlug'
    | '/tournaments/$tournamentId'
    | '/app/join/$code'
    | '/clubs/'
    | '/drills/'
    | '/players/'
    | '/tournaments/'
    | '/app/'
    | '/app/$clubSlug/challenges'
    | '/app/$clubSlug/club'
    | '/app/clubs/new'
    | '/app/$clubSlug/'
    | '/app/$clubSlug/drills/new'
    | '/app/$clubSlug/games/new'
    | '/app/$clubSlug/me/settings'
    | '/app/$clubSlug/ranking/daily'
    | '/app/$clubSlug/tournaments/$tournamentId'
    | '/app/$clubSlug/drills/'
    | '/app/$clubSlug/games/'
    | '/app/$clubSlug/me/'
    | '/app/$clubSlug/players/'
    | '/app/$clubSlug/ranking/'
    | '/app/$clubSlug/tournaments/'
    | '/app/$clubSlug/drills/$drillId/edit'
    | '/app/$clubSlug/me/training/plan'
    | '/app/$clubSlug/players/$playerId/settings'
    | '/app/$clubSlug/drills/$drillId/'
    | '/app/$clubSlug/me/training/'
    | '/app/$clubSlug/players/$playerId/'
    | '/app/$clubSlug/players/$playerId/training/plan'
    | '/app/$clubSlug/players/$playerId/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/search'
    | '/app/login'
    | '/auth/callback'
    | '/'
    | '/clubs/$slug'
    | '/drills/$drillId'
    | '/players/$playerSlug'
    | '/tournaments/$tournamentId'
    | '/app/join/$code'
    | '/clubs'
    | '/drills'
    | '/players'
    | '/tournaments'
    | '/app/$clubSlug/challenges'
    | '/app/$clubSlug/club'
    | '/app/clubs/new'
    | '/app/$clubSlug'
    | '/app/$clubSlug/drills/new'
    | '/app/$clubSlug/games/new'
    | '/app/$clubSlug/me/settings'
    | '/app/$clubSlug/ranking/daily'
    | '/app/$clubSlug/tournaments/$tournamentId'
    | '/app/$clubSlug/drills'
    | '/app/$clubSlug/games'
    | '/app/$clubSlug/me'
    | '/app/$clubSlug/players'
    | '/app/$clubSlug/ranking'
    | '/app/$clubSlug/tournaments'
    | '/app/$clubSlug/drills/$drillId/edit'
    | '/app/$clubSlug/me/training/plan'
    | '/app/$clubSlug/players/$playerId/settings'
    | '/app/$clubSlug/drills/$drillId'
    | '/app/$clubSlug/me/training'
    | '/app/$clubSlug/players/$playerId'
    | '/app/$clubSlug/players/$playerId/training/plan'
    | '/app/$clubSlug/players/$playerId/training'
  id:
    | '__root__'
    | '/_public'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app/_authed'
    | '/_public/search'
    | '/app/login'
    | '/auth/callback'
    | '/_public/'
    | '/app/_authed/$clubSlug'
    | '/_public/clubs/$slug'
    | '/_public/drills/$drillId'
    | '/_public/players/$playerSlug'
    | '/_public/tournaments/$tournamentId'
    | '/app/join/$code'
    | '/_public/clubs/'
    | '/_public/drills/'
    | '/_public/players/'
    | '/_public/tournaments/'
    | '/app/_authed/'
    | '/app/_authed/$clubSlug/challenges'
    | '/app/_authed/$clubSlug/club'
    | '/app/_authed/clubs/new'
    | '/app/_authed/$clubSlug/'
    | '/app/_authed/$clubSlug/drills/new'
    | '/app/_authed/$clubSlug/games/new'
    | '/app/_authed/$clubSlug/me/settings'
    | '/app/_authed/$clubSlug/ranking/daily'
    | '/app/_authed/$clubSlug/tournaments/$tournamentId'
    | '/app/_authed/$clubSlug/drills/'
    | '/app/_authed/$clubSlug/games/'
    | '/app/_authed/$clubSlug/me/'
    | '/app/_authed/$clubSlug/players/'
    | '/app/_authed/$clubSlug/ranking/'
    | '/app/_authed/$clubSlug/tournaments/'
    | '/app/_authed/$clubSlug/drills/$drillId/edit'
    | '/app/_authed/$clubSlug/me/training/plan'
    | '/app/_authed/$clubSlug/players/$playerId/settings'
    | '/app/_authed/$clubSlug/drills/$drillId/'
    | '/app/_authed/$clubSlug/me/training/'
    | '/app/_authed/$clubSlug/players/$playerId/'
    | '/app/_authed/$clubSlug/players/$playerId/training/plan'
    | '/app/_authed/$clubSlug/players/$playerId/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/clubs/': {
      id: '/_public/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof PublicClubsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/clubs/$slug': {
      id: '/_public/clubs/$slug'
      path: '/clubs/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof PublicClubsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/drills/': {
      id: '/_public/drills/'
      path: '/drills'
      fullPath: '/drills/'
      preLoaderRoute: typeof PublicDrillsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/drills/$drillId': {
      id: '/_public/drills/$drillId'
      path: '/drills/$drillId'
      fullPath: '/drills/$drillId'
      preLoaderRoute: typeof PublicDrillsDrillIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/players/': {
      id: '/_public/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PublicPlayersIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/players/$playerSlug': {
      id: '/_public/players/$playerSlug'
      path: '/players/$playerSlug'
      fullPath: '/players/$playerSlug'
      preLoaderRoute: typeof PublicPlayersPlayerSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/tournaments/': {
      id: '/_public/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof PublicTournamentsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/tournaments/$tournamentId': {
      id: '/_public/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof PublicTournamentsTournamentIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/app/_authed/': {
      id: '/app/_authed/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/_authed/$clubSlug': {
      id: '/app/_authed/$clubSlug'
      path: '/$clubSlug'
      fullPath: '/app/$clubSlug'
      preLoaderRoute: typeof AppAuthedClubSlugRouteRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/join/$code': {
      id: '/app/join/$code'
      path: '/join/$code'
      fullPath: '/app/join/$code'
      preLoaderRoute: typeof AppJoinCodeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_authed/$clubSlug/': {
      id: '/app/_authed/$clubSlug/'
      path: '/'
      fullPath: '/app/$clubSlug/'
      preLoaderRoute: typeof AppAuthedClubSlugIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/challenges': {
      id: '/app/_authed/$clubSlug/challenges'
      path: '/challenges'
      fullPath: '/app/$clubSlug/challenges'
      preLoaderRoute: typeof AppAuthedClubSlugChallengesRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/club': {
      id: '/app/_authed/$clubSlug/club'
      path: '/club'
      fullPath: '/app/$clubSlug/club'
      preLoaderRoute: typeof AppAuthedClubSlugClubRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/clubs/new': {
      id: '/app/_authed/clubs/new'
      path: '/clubs/new'
      fullPath: '/app/clubs/new'
      preLoaderRoute: typeof AppAuthedClubsNewRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/_authed/$clubSlug/drills/': {
      id: '/app/_authed/$clubSlug/drills/'
      path: '/drills'
      fullPath: '/app/$clubSlug/drills/'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/drills/new': {
      id: '/app/_authed/$clubSlug/drills/new'
      path: '/drills/new'
      fullPath: '/app/$clubSlug/drills/new'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsNewRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/games/': {
      id: '/app/_authed/$clubSlug/games/'
      path: '/games'
      fullPath: '/app/$clubSlug/games/'
      preLoaderRoute: typeof AppAuthedClubSlugGamesIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/games/new': {
      id: '/app/_authed/$clubSlug/games/new'
      path: '/games/new'
      fullPath: '/app/$clubSlug/games/new'
      preLoaderRoute: typeof AppAuthedClubSlugGamesNewRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/': {
      id: '/app/_authed/$clubSlug/me/'
      path: '/me'
      fullPath: '/app/$clubSlug/me/'
      preLoaderRoute: typeof AppAuthedClubSlugMeIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/settings': {
      id: '/app/_authed/$clubSlug/me/settings'
      path: '/me/settings'
      fullPath: '/app/$clubSlug/me/settings'
      preLoaderRoute: typeof AppAuthedClubSlugMeSettingsRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/': {
      id: '/app/_authed/$clubSlug/players/'
      path: '/players'
      fullPath: '/app/$clubSlug/players/'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/ranking/': {
      id: '/app/_authed/$clubSlug/ranking/'
      path: '/ranking'
      fullPath: '/app/$clubSlug/ranking/'
      preLoaderRoute: typeof AppAuthedClubSlugRankingIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/ranking/daily': {
      id: '/app/_authed/$clubSlug/ranking/daily'
      path: '/ranking/daily'
      fullPath: '/app/$clubSlug/ranking/daily'
      preLoaderRoute: typeof AppAuthedClubSlugRankingDailyRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/tournaments/': {
      id: '/app/_authed/$clubSlug/tournaments/'
      path: '/tournaments'
      fullPath: '/app/$clubSlug/tournaments/'
      preLoaderRoute: typeof AppAuthedClubSlugTournamentsIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/tournaments/$tournamentId': {
      id: '/app/_authed/$clubSlug/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/app/$clubSlug/tournaments/$tournamentId'
      preLoaderRoute: typeof AppAuthedClubSlugTournamentsTournamentIdRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/drills/$drillId/': {
      id: '/app/_authed/$clubSlug/drills/$drillId/'
      path: '/drills/$drillId'
      fullPath: '/app/$clubSlug/drills/$drillId/'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsDrillIdIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/drills/$drillId/edit': {
      id: '/app/_authed/$clubSlug/drills/$drillId/edit'
      path: '/drills/$drillId/edit'
      fullPath: '/app/$clubSlug/drills/$drillId/edit'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsDrillIdEditRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/training/': {
      id: '/app/_authed/$clubSlug/me/training/'
      path: '/me/training'
      fullPath: '/app/$clubSlug/me/training/'
      preLoaderRoute: typeof AppAuthedClubSlugMeTrainingIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/training/plan': {
      id: '/app/_authed/$clubSlug/me/training/plan'
      path: '/me/training/plan'
      fullPath: '/app/$clubSlug/me/training/plan'
      preLoaderRoute: typeof AppAuthedClubSlugMeTrainingPlanRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/': {
      id: '/app/_authed/$clubSlug/players/$playerId/'
      path: '/players/$playerId'
      fullPath: '/app/$clubSlug/players/$playerId/'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/settings': {
      id: '/app/_authed/$clubSlug/players/$playerId/settings'
      path: '/players/$playerId/settings'
      fullPath: '/app/$clubSlug/players/$playerId/settings'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdSettingsRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/training/': {
      id: '/app/_authed/$clubSlug/players/$playerId/training/'
      path: '/players/$playerId/training'
      fullPath: '/app/$clubSlug/players/$playerId/training/'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/training/plan': {
      id: '/app/_authed/$clubSlug/players/$playerId/training/plan'
      path: '/players/$playerId/training/plan'
      fullPath: '/app/$clubSlug/players/$playerId/training/plan'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicClubsSlugRoute: typeof PublicClubsSlugRoute
  PublicDrillsDrillIdRoute: typeof PublicDrillsDrillIdRoute
  PublicPlayersPlayerSlugRoute: typeof PublicPlayersPlayerSlugRoute
  PublicTournamentsTournamentIdRoute: typeof PublicTournamentsTournamentIdRoute
  PublicClubsIndexRoute: typeof PublicClubsIndexRoute
  PublicDrillsIndexRoute: typeof PublicDrillsIndexRoute
  PublicPlayersIndexRoute: typeof PublicPlayersIndexRoute
  PublicTournamentsIndexRoute: typeof PublicTournamentsIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicClubsSlugRoute: PublicClubsSlugRoute,
  PublicDrillsDrillIdRoute: PublicDrillsDrillIdRoute,
  PublicPlayersPlayerSlugRoute: PublicPlayersPlayerSlugRoute,
  PublicTournamentsTournamentIdRoute: PublicTournamentsTournamentIdRoute,
  PublicClubsIndexRoute: PublicClubsIndexRoute,
  PublicDrillsIndexRoute: PublicDrillsIndexRoute,
  PublicPlayersIndexRoute: PublicPlayersIndexRoute,
  PublicTournamentsIndexRoute: PublicTournamentsIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AppAuthedClubSlugRouteRouteChildren {
  AppAuthedClubSlugChallengesRoute: typeof AppAuthedClubSlugChallengesRoute
  AppAuthedClubSlugClubRoute: typeof AppAuthedClubSlugClubRoute
  AppAuthedClubSlugIndexRoute: typeof AppAuthedClubSlugIndexRoute
  AppAuthedClubSlugDrillsNewRoute: typeof AppAuthedClubSlugDrillsNewRoute
  AppAuthedClubSlugGamesNewRoute: typeof AppAuthedClubSlugGamesNewRoute
  AppAuthedClubSlugMeSettingsRoute: typeof AppAuthedClubSlugMeSettingsRoute
  AppAuthedClubSlugRankingDailyRoute: typeof AppAuthedClubSlugRankingDailyRoute
  AppAuthedClubSlugTournamentsTournamentIdRoute: typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  AppAuthedClubSlugDrillsIndexRoute: typeof AppAuthedClubSlugDrillsIndexRoute
  AppAuthedClubSlugGamesIndexRoute: typeof AppAuthedClubSlugGamesIndexRoute
  AppAuthedClubSlugMeIndexRoute: typeof AppAuthedClubSlugMeIndexRoute
  AppAuthedClubSlugPlayersIndexRoute: typeof AppAuthedClubSlugPlayersIndexRoute
  AppAuthedClubSlugRankingIndexRoute: typeof AppAuthedClubSlugRankingIndexRoute
  AppAuthedClubSlugTournamentsIndexRoute: typeof AppAuthedClubSlugTournamentsIndexRoute
  AppAuthedClubSlugDrillsDrillIdEditRoute: typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  AppAuthedClubSlugMeTrainingPlanRoute: typeof AppAuthedClubSlugMeTrainingPlanRoute
  AppAuthedClubSlugPlayersPlayerIdSettingsRoute: typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  AppAuthedClubSlugDrillsDrillIdIndexRoute: typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  AppAuthedClubSlugMeTrainingIndexRoute: typeof AppAuthedClubSlugMeTrainingIndexRoute
  AppAuthedClubSlugPlayersPlayerIdIndexRoute: typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}

const AppAuthedClubSlugRouteRouteChildren: AppAuthedClubSlugRouteRouteChildren =
  {
    AppAuthedClubSlugChallengesRoute: AppAuthedClubSlugChallengesRoute,
    AppAuthedClubSlugClubRoute: AppAuthedClubSlugClubRoute,
    AppAuthedClubSlugIndexRoute: AppAuthedClubSlugIndexRoute,
    AppAuthedClubSlugDrillsNewRoute: AppAuthedClubSlugDrillsNewRoute,
    AppAuthedClubSlugGamesNewRoute: AppAuthedClubSlugGamesNewRoute,
    AppAuthedClubSlugMeSettingsRoute: AppAuthedClubSlugMeSettingsRoute,
    AppAuthedClubSlugRankingDailyRoute: AppAuthedClubSlugRankingDailyRoute,
    AppAuthedClubSlugTournamentsTournamentIdRoute:
      AppAuthedClubSlugTournamentsTournamentIdRoute,
    AppAuthedClubSlugDrillsIndexRoute: AppAuthedClubSlugDrillsIndexRoute,
    AppAuthedClubSlugGamesIndexRoute: AppAuthedClubSlugGamesIndexRoute,
    AppAuthedClubSlugMeIndexRoute: AppAuthedClubSlugMeIndexRoute,
    AppAuthedClubSlugPlayersIndexRoute: AppAuthedClubSlugPlayersIndexRoute,
    AppAuthedClubSlugRankingIndexRoute: AppAuthedClubSlugRankingIndexRoute,
    AppAuthedClubSlugTournamentsIndexRoute:
      AppAuthedClubSlugTournamentsIndexRoute,
    AppAuthedClubSlugDrillsDrillIdEditRoute:
      AppAuthedClubSlugDrillsDrillIdEditRoute,
    AppAuthedClubSlugMeTrainingPlanRoute: AppAuthedClubSlugMeTrainingPlanRoute,
    AppAuthedClubSlugPlayersPlayerIdSettingsRoute:
      AppAuthedClubSlugPlayersPlayerIdSettingsRoute,
    AppAuthedClubSlugDrillsDrillIdIndexRoute:
      AppAuthedClubSlugDrillsDrillIdIndexRoute,
    AppAuthedClubSlugMeTrainingIndexRoute:
      AppAuthedClubSlugMeTrainingIndexRoute,
    AppAuthedClubSlugPlayersPlayerIdIndexRoute:
      AppAuthedClubSlugPlayersPlayerIdIndexRoute,
    AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute:
      AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute,
    AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute:
      AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute,
  }

const AppAuthedClubSlugRouteRouteWithChildren =
  AppAuthedClubSlugRouteRoute._addFileChildren(
    AppAuthedClubSlugRouteRouteChildren,
  )

interface AppAuthedRouteRouteChildren {
  AppAuthedClubSlugRouteRoute: typeof AppAuthedClubSlugRouteRouteWithChildren
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
  AppAuthedClubsNewRoute: typeof AppAuthedClubsNewRoute
}

const AppAuthedRouteRouteChildren: AppAuthedRouteRouteChildren = {
  AppAuthedClubSlugRouteRoute: AppAuthedClubSlugRouteRouteWithChildren,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
  AppAuthedClubsNewRoute: AppAuthedClubsNewRoute,
}

const AppAuthedRouteRouteWithChildren = AppAuthedRouteRoute._addFileChildren(
  AppAuthedRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAuthedRouteRoute: typeof AppAuthedRouteRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppJoinCodeRoute: typeof AppJoinCodeRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthedRouteRoute: AppAuthedRouteRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppJoinCodeRoute: AppJoinCodeRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
