/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as DrillsRouteImport } from './routes/drills'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as AppAuthedRouteRouteImport } from './routes/app/_authed/route'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppAuthedIndexRouteImport } from './routes/app/_authed/index'
import { Route as AppAuthedClubSlugRouteRouteImport } from './routes/app/_authed/$clubSlug/route'
import { Route as AppJoinCodeRouteImport } from './routes/app/join.$code'
import { Route as AppAuthedClubSlugIndexRouteImport } from './routes/app/_authed/$clubSlug/index'
import { Route as AppAuthedClubSlugChallengesRouteImport } from './routes/app/_authed/$clubSlug/challenges'
import { Route as AppAuthedClubSlugClubRouteImport } from './routes/app/_authed/$clubSlug/club'
import { Route as AppAuthedClubsNewRouteImport } from './routes/app/_authed/clubs.new'
import { Route as AppAuthedClubSlugDrillsIndexRouteImport } from './routes/app/_authed/$clubSlug/drills/index'
import { Route as AppAuthedClubSlugDrillsNewRouteImport } from './routes/app/_authed/$clubSlug/drills/new'
import { Route as AppAuthedClubSlugGamesIndexRouteImport } from './routes/app/_authed/$clubSlug/games/index'
import { Route as AppAuthedClubSlugGamesNewRouteImport } from './routes/app/_authed/$clubSlug/games/new'
import { Route as AppAuthedClubSlugMeIndexRouteImport } from './routes/app/_authed/$clubSlug/me/index'
import { Route as AppAuthedClubSlugMeSettingsRouteImport } from './routes/app/_authed/$clubSlug/me/settings'
import { Route as AppAuthedClubSlugPlayersIndexRouteImport } from './routes/app/_authed/$clubSlug/players/index'
import { Route as AppAuthedClubSlugRankingIndexRouteImport } from './routes/app/_authed/$clubSlug/ranking/index'
import { Route as AppAuthedClubSlugRankingDailyRouteImport } from './routes/app/_authed/$clubSlug/ranking/daily'
import { Route as AppAuthedClubSlugTournamentsIndexRouteImport } from './routes/app/_authed/$clubSlug/tournaments/index'
import { Route as AppAuthedClubSlugTournamentsTournamentIdRouteImport } from './routes/app/_authed/$clubSlug/tournaments/$tournamentId'
import { Route as AppAuthedClubSlugDrillsDrillIdIndexRouteImport } from './routes/app/_authed/$clubSlug/drills/$drillId/index'
import { Route as AppAuthedClubSlugDrillsDrillIdEditRouteImport } from './routes/app/_authed/$clubSlug/drills/$drillId/edit'
import { Route as AppAuthedClubSlugMeTrainingIndexRouteImport } from './routes/app/_authed/$clubSlug/me/training/index'
import { Route as AppAuthedClubSlugMeTrainingPlanRouteImport } from './routes/app/_authed/$clubSlug/me/training/plan'
import { Route as AppAuthedClubSlugPlayersPlayerIdIndexRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/index'
import { Route as AppAuthedClubSlugPlayersPlayerIdSettingsRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/settings'
import { Route as AppAuthedClubSlugPlayersPlayerIdTrainingIndexRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/training/index'
import { Route as AppAuthedClubSlugPlayersPlayerIdTrainingPlanRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/training/plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsRoute = DrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRouteRoute = AppAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedClubSlugRouteRoute = AppAuthedClubSlugRouteRouteImport.update({
  id: '/$clubSlug',
  path: '/$clubSlug',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppJoinCodeRoute = AppJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthedClubSlugIndexRoute = AppAuthedClubSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedClubSlugRouteRoute,
} as any)
const AppAuthedClubSlugChallengesRoute =
  AppAuthedClubSlugChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugClubRoute = AppAuthedClubSlugClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => AppAuthedClubSlugRouteRoute,
} as any)
const AppAuthedClubsNewRoute = AppAuthedClubsNewRouteImport.update({
  id: '/clubs/new',
  path: '/clubs/new',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedClubSlugDrillsIndexRoute =
  AppAuthedClubSlugDrillsIndexRouteImport.update({
    id: '/drills/',
    path: '/drills/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugDrillsNewRoute =
  AppAuthedClubSlugDrillsNewRouteImport.update({
    id: '/drills/new',
    path: '/drills/new',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugGamesIndexRoute =
  AppAuthedClubSlugGamesIndexRouteImport.update({
    id: '/games/',
    path: '/games/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugGamesNewRoute =
  AppAuthedClubSlugGamesNewRouteImport.update({
    id: '/games/new',
    path: '/games/new',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeIndexRoute =
  AppAuthedClubSlugMeIndexRouteImport.update({
    id: '/me/',
    path: '/me/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeSettingsRoute =
  AppAuthedClubSlugMeSettingsRouteImport.update({
    id: '/me/settings',
    path: '/me/settings',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersIndexRoute =
  AppAuthedClubSlugPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugRankingIndexRoute =
  AppAuthedClubSlugRankingIndexRouteImport.update({
    id: '/ranking/',
    path: '/ranking/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugRankingDailyRoute =
  AppAuthedClubSlugRankingDailyRouteImport.update({
    id: '/ranking/daily',
    path: '/ranking/daily',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugTournamentsIndexRoute =
  AppAuthedClubSlugTournamentsIndexRouteImport.update({
    id: '/tournaments/',
    path: '/tournaments/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugTournamentsTournamentIdRoute =
  AppAuthedClubSlugTournamentsTournamentIdRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugDrillsDrillIdIndexRoute =
  AppAuthedClubSlugDrillsDrillIdIndexRouteImport.update({
    id: '/drills/$drillId/',
    path: '/drills/$drillId/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugDrillsDrillIdEditRoute =
  AppAuthedClubSlugDrillsDrillIdEditRouteImport.update({
    id: '/drills/$drillId/edit',
    path: '/drills/$drillId/edit',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeTrainingIndexRoute =
  AppAuthedClubSlugMeTrainingIndexRouteImport.update({
    id: '/me/training/',
    path: '/me/training/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeTrainingPlanRoute =
  AppAuthedClubSlugMeTrainingPlanRouteImport.update({
    id: '/me/training/plan',
    path: '/me/training/plan',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdIndexRoute =
  AppAuthedClubSlugPlayersPlayerIdIndexRouteImport.update({
    id: '/players/$playerId/',
    path: '/players/$playerId/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdSettingsRoute =
  AppAuthedClubSlugPlayersPlayerIdSettingsRouteImport.update({
    id: '/players/$playerId/settings',
    path: '/players/$playerId/settings',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute =
  AppAuthedClubSlugPlayersPlayerIdTrainingIndexRouteImport.update({
    id: '/players/$playerId/training/',
    path: '/players/$playerId/training/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute =
  AppAuthedClubSlugPlayersPlayerIdTrainingPlanRouteImport.update({
    id: '/players/$playerId/training/plan',
    path: '/players/$playerId/training/plan',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/clubs': typeof ClubsRoute
  '/drills': typeof DrillsRoute
  '/tournaments': typeof TournamentsRoute
  '/app/login': typeof AppLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/$clubSlug': typeof AppAuthedClubSlugRouteRouteWithChildren
  '/app/join/$code': typeof AppJoinCodeRoute
  '/app/': typeof AppAuthedIndexRoute
  '/app/$clubSlug/challenges': typeof AppAuthedClubSlugChallengesRoute
  '/app/$clubSlug/club': typeof AppAuthedClubSlugClubRoute
  '/app/clubs/new': typeof AppAuthedClubsNewRoute
  '/app/$clubSlug/': typeof AppAuthedClubSlugIndexRoute
  '/app/$clubSlug/drills/new': typeof AppAuthedClubSlugDrillsNewRoute
  '/app/$clubSlug/games/new': typeof AppAuthedClubSlugGamesNewRoute
  '/app/$clubSlug/me/settings': typeof AppAuthedClubSlugMeSettingsRoute
  '/app/$clubSlug/ranking/daily': typeof AppAuthedClubSlugRankingDailyRoute
  '/app/$clubSlug/tournaments/$tournamentId': typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  '/app/$clubSlug/drills/': typeof AppAuthedClubSlugDrillsIndexRoute
  '/app/$clubSlug/games/': typeof AppAuthedClubSlugGamesIndexRoute
  '/app/$clubSlug/me/': typeof AppAuthedClubSlugMeIndexRoute
  '/app/$clubSlug/players/': typeof AppAuthedClubSlugPlayersIndexRoute
  '/app/$clubSlug/ranking/': typeof AppAuthedClubSlugRankingIndexRoute
  '/app/$clubSlug/tournaments/': typeof AppAuthedClubSlugTournamentsIndexRoute
  '/app/$clubSlug/drills/$drillId/edit': typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  '/app/$clubSlug/me/training/plan': typeof AppAuthedClubSlugMeTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/settings': typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  '/app/$clubSlug/drills/$drillId/': typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  '/app/$clubSlug/me/training/': typeof AppAuthedClubSlugMeTrainingIndexRoute
  '/app/$clubSlug/players/$playerId/': typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  '/app/$clubSlug/players/$playerId/training/plan': typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/training/': typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAuthedIndexRoute
  '/clubs': typeof ClubsRoute
  '/drills': typeof DrillsRoute
  '/tournaments': typeof TournamentsRoute
  '/app/login': typeof AppLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/join/$code': typeof AppJoinCodeRoute
  '/app/$clubSlug/challenges': typeof AppAuthedClubSlugChallengesRoute
  '/app/$clubSlug/club': typeof AppAuthedClubSlugClubRoute
  '/app/clubs/new': typeof AppAuthedClubsNewRoute
  '/app/$clubSlug': typeof AppAuthedClubSlugIndexRoute
  '/app/$clubSlug/drills/new': typeof AppAuthedClubSlugDrillsNewRoute
  '/app/$clubSlug/games/new': typeof AppAuthedClubSlugGamesNewRoute
  '/app/$clubSlug/me/settings': typeof AppAuthedClubSlugMeSettingsRoute
  '/app/$clubSlug/ranking/daily': typeof AppAuthedClubSlugRankingDailyRoute
  '/app/$clubSlug/tournaments/$tournamentId': typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  '/app/$clubSlug/drills': typeof AppAuthedClubSlugDrillsIndexRoute
  '/app/$clubSlug/games': typeof AppAuthedClubSlugGamesIndexRoute
  '/app/$clubSlug/me': typeof AppAuthedClubSlugMeIndexRoute
  '/app/$clubSlug/players': typeof AppAuthedClubSlugPlayersIndexRoute
  '/app/$clubSlug/ranking': typeof AppAuthedClubSlugRankingIndexRoute
  '/app/$clubSlug/tournaments': typeof AppAuthedClubSlugTournamentsIndexRoute
  '/app/$clubSlug/drills/$drillId/edit': typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  '/app/$clubSlug/me/training/plan': typeof AppAuthedClubSlugMeTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/settings': typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  '/app/$clubSlug/drills/$drillId': typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  '/app/$clubSlug/me/training': typeof AppAuthedClubSlugMeTrainingIndexRoute
  '/app/$clubSlug/players/$playerId': typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  '/app/$clubSlug/players/$playerId/training/plan': typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/training': typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/clubs': typeof ClubsRoute
  '/drills': typeof DrillsRoute
  '/tournaments': typeof TournamentsRoute
  '/app/_authed': typeof AppAuthedRouteRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/_authed/$clubSlug': typeof AppAuthedClubSlugRouteRouteWithChildren
  '/app/join/$code': typeof AppJoinCodeRoute
  '/app/_authed/': typeof AppAuthedIndexRoute
  '/app/_authed/$clubSlug/challenges': typeof AppAuthedClubSlugChallengesRoute
  '/app/_authed/$clubSlug/club': typeof AppAuthedClubSlugClubRoute
  '/app/_authed/clubs/new': typeof AppAuthedClubsNewRoute
  '/app/_authed/$clubSlug/': typeof AppAuthedClubSlugIndexRoute
  '/app/_authed/$clubSlug/drills/new': typeof AppAuthedClubSlugDrillsNewRoute
  '/app/_authed/$clubSlug/games/new': typeof AppAuthedClubSlugGamesNewRoute
  '/app/_authed/$clubSlug/me/settings': typeof AppAuthedClubSlugMeSettingsRoute
  '/app/_authed/$clubSlug/ranking/daily': typeof AppAuthedClubSlugRankingDailyRoute
  '/app/_authed/$clubSlug/tournaments/$tournamentId': typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  '/app/_authed/$clubSlug/drills/': typeof AppAuthedClubSlugDrillsIndexRoute
  '/app/_authed/$clubSlug/games/': typeof AppAuthedClubSlugGamesIndexRoute
  '/app/_authed/$clubSlug/me/': typeof AppAuthedClubSlugMeIndexRoute
  '/app/_authed/$clubSlug/players/': typeof AppAuthedClubSlugPlayersIndexRoute
  '/app/_authed/$clubSlug/ranking/': typeof AppAuthedClubSlugRankingIndexRoute
  '/app/_authed/$clubSlug/tournaments/': typeof AppAuthedClubSlugTournamentsIndexRoute
  '/app/_authed/$clubSlug/drills/$drillId/edit': typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  '/app/_authed/$clubSlug/me/training/plan': typeof AppAuthedClubSlugMeTrainingPlanRoute
  '/app/_authed/$clubSlug/players/$playerId/settings': typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  '/app/_authed/$clubSlug/drills/$drillId/': typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  '/app/_authed/$clubSlug/me/training/': typeof AppAuthedClubSlugMeTrainingIndexRoute
  '/app/_authed/$clubSlug/players/$playerId/': typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  '/app/_authed/$clubSlug/players/$playerId/training/plan': typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  '/app/_authed/$clubSlug/players/$playerId/training/': typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/clubs'
    | '/drills'
    | '/tournaments'
    | '/app/login'
    | '/auth/callback'
    | '/app/$clubSlug'
    | '/app/join/$code'
    | '/app/'
    | '/app/$clubSlug/challenges'
    | '/app/$clubSlug/club'
    | '/app/clubs/new'
    | '/app/$clubSlug/'
    | '/app/$clubSlug/drills/new'
    | '/app/$clubSlug/games/new'
    | '/app/$clubSlug/me/settings'
    | '/app/$clubSlug/ranking/daily'
    | '/app/$clubSlug/tournaments/$tournamentId'
    | '/app/$clubSlug/drills/'
    | '/app/$clubSlug/games/'
    | '/app/$clubSlug/me/'
    | '/app/$clubSlug/players/'
    | '/app/$clubSlug/ranking/'
    | '/app/$clubSlug/tournaments/'
    | '/app/$clubSlug/drills/$drillId/edit'
    | '/app/$clubSlug/me/training/plan'
    | '/app/$clubSlug/players/$playerId/settings'
    | '/app/$clubSlug/drills/$drillId/'
    | '/app/$clubSlug/me/training/'
    | '/app/$clubSlug/players/$playerId/'
    | '/app/$clubSlug/players/$playerId/training/plan'
    | '/app/$clubSlug/players/$playerId/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/clubs'
    | '/drills'
    | '/tournaments'
    | '/app/login'
    | '/auth/callback'
    | '/app/join/$code'
    | '/app/$clubSlug/challenges'
    | '/app/$clubSlug/club'
    | '/app/clubs/new'
    | '/app/$clubSlug'
    | '/app/$clubSlug/drills/new'
    | '/app/$clubSlug/games/new'
    | '/app/$clubSlug/me/settings'
    | '/app/$clubSlug/ranking/daily'
    | '/app/$clubSlug/tournaments/$tournamentId'
    | '/app/$clubSlug/drills'
    | '/app/$clubSlug/games'
    | '/app/$clubSlug/me'
    | '/app/$clubSlug/players'
    | '/app/$clubSlug/ranking'
    | '/app/$clubSlug/tournaments'
    | '/app/$clubSlug/drills/$drillId/edit'
    | '/app/$clubSlug/me/training/plan'
    | '/app/$clubSlug/players/$playerId/settings'
    | '/app/$clubSlug/drills/$drillId'
    | '/app/$clubSlug/me/training'
    | '/app/$clubSlug/players/$playerId'
    | '/app/$clubSlug/players/$playerId/training/plan'
    | '/app/$clubSlug/players/$playerId/training'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/clubs'
    | '/drills'
    | '/tournaments'
    | '/app/_authed'
    | '/app/login'
    | '/auth/callback'
    | '/app/_authed/$clubSlug'
    | '/app/join/$code'
    | '/app/_authed/'
    | '/app/_authed/$clubSlug/challenges'
    | '/app/_authed/$clubSlug/club'
    | '/app/_authed/clubs/new'
    | '/app/_authed/$clubSlug/'
    | '/app/_authed/$clubSlug/drills/new'
    | '/app/_authed/$clubSlug/games/new'
    | '/app/_authed/$clubSlug/me/settings'
    | '/app/_authed/$clubSlug/ranking/daily'
    | '/app/_authed/$clubSlug/tournaments/$tournamentId'
    | '/app/_authed/$clubSlug/drills/'
    | '/app/_authed/$clubSlug/games/'
    | '/app/_authed/$clubSlug/me/'
    | '/app/_authed/$clubSlug/players/'
    | '/app/_authed/$clubSlug/ranking/'
    | '/app/_authed/$clubSlug/tournaments/'
    | '/app/_authed/$clubSlug/drills/$drillId/edit'
    | '/app/_authed/$clubSlug/me/training/plan'
    | '/app/_authed/$clubSlug/players/$playerId/settings'
    | '/app/_authed/$clubSlug/drills/$drillId/'
    | '/app/_authed/$clubSlug/me/training/'
    | '/app/_authed/$clubSlug/players/$playerId/'
    | '/app/_authed/$clubSlug/players/$playerId/training/plan'
    | '/app/_authed/$clubSlug/players/$playerId/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ClubsRoute: typeof ClubsRoute
  DrillsRoute: typeof DrillsRoute
  TournamentsRoute: typeof TournamentsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills': {
      id: '/drills'
      path: '/drills'
      fullPath: '/drills'
      preLoaderRoute: typeof DrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed/': {
      id: '/app/_authed/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/_authed/$clubSlug': {
      id: '/app/_authed/$clubSlug'
      path: '/$clubSlug'
      fullPath: '/app/$clubSlug'
      preLoaderRoute: typeof AppAuthedClubSlugRouteRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/join/$code': {
      id: '/app/join/$code'
      path: '/join/$code'
      fullPath: '/app/join/$code'
      preLoaderRoute: typeof AppJoinCodeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_authed/$clubSlug/': {
      id: '/app/_authed/$clubSlug/'
      path: '/'
      fullPath: '/app/$clubSlug/'
      preLoaderRoute: typeof AppAuthedClubSlugIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/challenges': {
      id: '/app/_authed/$clubSlug/challenges'
      path: '/challenges'
      fullPath: '/app/$clubSlug/challenges'
      preLoaderRoute: typeof AppAuthedClubSlugChallengesRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/club': {
      id: '/app/_authed/$clubSlug/club'
      path: '/club'
      fullPath: '/app/$clubSlug/club'
      preLoaderRoute: typeof AppAuthedClubSlugClubRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/clubs/new': {
      id: '/app/_authed/clubs/new'
      path: '/clubs/new'
      fullPath: '/app/clubs/new'
      preLoaderRoute: typeof AppAuthedClubsNewRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/_authed/$clubSlug/drills/': {
      id: '/app/_authed/$clubSlug/drills/'
      path: '/drills'
      fullPath: '/app/$clubSlug/drills/'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/drills/new': {
      id: '/app/_authed/$clubSlug/drills/new'
      path: '/drills/new'
      fullPath: '/app/$clubSlug/drills/new'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsNewRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/games/': {
      id: '/app/_authed/$clubSlug/games/'
      path: '/games'
      fullPath: '/app/$clubSlug/games/'
      preLoaderRoute: typeof AppAuthedClubSlugGamesIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/games/new': {
      id: '/app/_authed/$clubSlug/games/new'
      path: '/games/new'
      fullPath: '/app/$clubSlug/games/new'
      preLoaderRoute: typeof AppAuthedClubSlugGamesNewRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/': {
      id: '/app/_authed/$clubSlug/me/'
      path: '/me'
      fullPath: '/app/$clubSlug/me/'
      preLoaderRoute: typeof AppAuthedClubSlugMeIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/settings': {
      id: '/app/_authed/$clubSlug/me/settings'
      path: '/me/settings'
      fullPath: '/app/$clubSlug/me/settings'
      preLoaderRoute: typeof AppAuthedClubSlugMeSettingsRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/': {
      id: '/app/_authed/$clubSlug/players/'
      path: '/players'
      fullPath: '/app/$clubSlug/players/'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/ranking/': {
      id: '/app/_authed/$clubSlug/ranking/'
      path: '/ranking'
      fullPath: '/app/$clubSlug/ranking/'
      preLoaderRoute: typeof AppAuthedClubSlugRankingIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/ranking/daily': {
      id: '/app/_authed/$clubSlug/ranking/daily'
      path: '/ranking/daily'
      fullPath: '/app/$clubSlug/ranking/daily'
      preLoaderRoute: typeof AppAuthedClubSlugRankingDailyRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/tournaments/': {
      id: '/app/_authed/$clubSlug/tournaments/'
      path: '/tournaments'
      fullPath: '/app/$clubSlug/tournaments/'
      preLoaderRoute: typeof AppAuthedClubSlugTournamentsIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/tournaments/$tournamentId': {
      id: '/app/_authed/$clubSlug/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/app/$clubSlug/tournaments/$tournamentId'
      preLoaderRoute: typeof AppAuthedClubSlugTournamentsTournamentIdRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/drills/$drillId/': {
      id: '/app/_authed/$clubSlug/drills/$drillId/'
      path: '/drills/$drillId'
      fullPath: '/app/$clubSlug/drills/$drillId/'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsDrillIdIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/drills/$drillId/edit': {
      id: '/app/_authed/$clubSlug/drills/$drillId/edit'
      path: '/drills/$drillId/edit'
      fullPath: '/app/$clubSlug/drills/$drillId/edit'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsDrillIdEditRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/training/': {
      id: '/app/_authed/$clubSlug/me/training/'
      path: '/me/training'
      fullPath: '/app/$clubSlug/me/training/'
      preLoaderRoute: typeof AppAuthedClubSlugMeTrainingIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/training/plan': {
      id: '/app/_authed/$clubSlug/me/training/plan'
      path: '/me/training/plan'
      fullPath: '/app/$clubSlug/me/training/plan'
      preLoaderRoute: typeof AppAuthedClubSlugMeTrainingPlanRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/': {
      id: '/app/_authed/$clubSlug/players/$playerId/'
      path: '/players/$playerId'
      fullPath: '/app/$clubSlug/players/$playerId/'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/settings': {
      id: '/app/_authed/$clubSlug/players/$playerId/settings'
      path: '/players/$playerId/settings'
      fullPath: '/app/$clubSlug/players/$playerId/settings'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdSettingsRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/training/': {
      id: '/app/_authed/$clubSlug/players/$playerId/training/'
      path: '/players/$playerId/training'
      fullPath: '/app/$clubSlug/players/$playerId/training/'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/training/plan': {
      id: '/app/_authed/$clubSlug/players/$playerId/training/plan'
      path: '/players/$playerId/training/plan'
      fullPath: '/app/$clubSlug/players/$playerId/training/plan'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
  }
}

interface AppAuthedClubSlugRouteRouteChildren {
  AppAuthedClubSlugChallengesRoute: typeof AppAuthedClubSlugChallengesRoute
  AppAuthedClubSlugClubRoute: typeof AppAuthedClubSlugClubRoute
  AppAuthedClubSlugIndexRoute: typeof AppAuthedClubSlugIndexRoute
  AppAuthedClubSlugDrillsNewRoute: typeof AppAuthedClubSlugDrillsNewRoute
  AppAuthedClubSlugGamesNewRoute: typeof AppAuthedClubSlugGamesNewRoute
  AppAuthedClubSlugMeSettingsRoute: typeof AppAuthedClubSlugMeSettingsRoute
  AppAuthedClubSlugRankingDailyRoute: typeof AppAuthedClubSlugRankingDailyRoute
  AppAuthedClubSlugTournamentsTournamentIdRoute: typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  AppAuthedClubSlugDrillsIndexRoute: typeof AppAuthedClubSlugDrillsIndexRoute
  AppAuthedClubSlugGamesIndexRoute: typeof AppAuthedClubSlugGamesIndexRoute
  AppAuthedClubSlugMeIndexRoute: typeof AppAuthedClubSlugMeIndexRoute
  AppAuthedClubSlugPlayersIndexRoute: typeof AppAuthedClubSlugPlayersIndexRoute
  AppAuthedClubSlugRankingIndexRoute: typeof AppAuthedClubSlugRankingIndexRoute
  AppAuthedClubSlugTournamentsIndexRoute: typeof AppAuthedClubSlugTournamentsIndexRoute
  AppAuthedClubSlugDrillsDrillIdEditRoute: typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  AppAuthedClubSlugMeTrainingPlanRoute: typeof AppAuthedClubSlugMeTrainingPlanRoute
  AppAuthedClubSlugPlayersPlayerIdSettingsRoute: typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  AppAuthedClubSlugDrillsDrillIdIndexRoute: typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  AppAuthedClubSlugMeTrainingIndexRoute: typeof AppAuthedClubSlugMeTrainingIndexRoute
  AppAuthedClubSlugPlayersPlayerIdIndexRoute: typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}

const AppAuthedClubSlugRouteRouteChildren: AppAuthedClubSlugRouteRouteChildren =
  {
    AppAuthedClubSlugChallengesRoute: AppAuthedClubSlugChallengesRoute,
    AppAuthedClubSlugClubRoute: AppAuthedClubSlugClubRoute,
    AppAuthedClubSlugIndexRoute: AppAuthedClubSlugIndexRoute,
    AppAuthedClubSlugDrillsNewRoute: AppAuthedClubSlugDrillsNewRoute,
    AppAuthedClubSlugGamesNewRoute: AppAuthedClubSlugGamesNewRoute,
    AppAuthedClubSlugMeSettingsRoute: AppAuthedClubSlugMeSettingsRoute,
    AppAuthedClubSlugRankingDailyRoute: AppAuthedClubSlugRankingDailyRoute,
    AppAuthedClubSlugTournamentsTournamentIdRoute:
      AppAuthedClubSlugTournamentsTournamentIdRoute,
    AppAuthedClubSlugDrillsIndexRoute: AppAuthedClubSlugDrillsIndexRoute,
    AppAuthedClubSlugGamesIndexRoute: AppAuthedClubSlugGamesIndexRoute,
    AppAuthedClubSlugMeIndexRoute: AppAuthedClubSlugMeIndexRoute,
    AppAuthedClubSlugPlayersIndexRoute: AppAuthedClubSlugPlayersIndexRoute,
    AppAuthedClubSlugRankingIndexRoute: AppAuthedClubSlugRankingIndexRoute,
    AppAuthedClubSlugTournamentsIndexRoute:
      AppAuthedClubSlugTournamentsIndexRoute,
    AppAuthedClubSlugDrillsDrillIdEditRoute:
      AppAuthedClubSlugDrillsDrillIdEditRoute,
    AppAuthedClubSlugMeTrainingPlanRoute: AppAuthedClubSlugMeTrainingPlanRoute,
    AppAuthedClubSlugPlayersPlayerIdSettingsRoute:
      AppAuthedClubSlugPlayersPlayerIdSettingsRoute,
    AppAuthedClubSlugDrillsDrillIdIndexRoute:
      AppAuthedClubSlugDrillsDrillIdIndexRoute,
    AppAuthedClubSlugMeTrainingIndexRoute:
      AppAuthedClubSlugMeTrainingIndexRoute,
    AppAuthedClubSlugPlayersPlayerIdIndexRoute:
      AppAuthedClubSlugPlayersPlayerIdIndexRoute,
    AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute:
      AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute,
    AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute:
      AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute,
  }

const AppAuthedClubSlugRouteRouteWithChildren =
  AppAuthedClubSlugRouteRoute._addFileChildren(
    AppAuthedClubSlugRouteRouteChildren,
  )

interface AppAuthedRouteRouteChildren {
  AppAuthedClubSlugRouteRoute: typeof AppAuthedClubSlugRouteRouteWithChildren
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
  AppAuthedClubsNewRoute: typeof AppAuthedClubsNewRoute
}

const AppAuthedRouteRouteChildren: AppAuthedRouteRouteChildren = {
  AppAuthedClubSlugRouteRoute: AppAuthedClubSlugRouteRouteWithChildren,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
  AppAuthedClubsNewRoute: AppAuthedClubsNewRoute,
}

const AppAuthedRouteRouteWithChildren = AppAuthedRouteRoute._addFileChildren(
  AppAuthedRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAuthedRouteRoute: typeof AppAuthedRouteRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppJoinCodeRoute: typeof AppJoinCodeRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthedRouteRoute: AppAuthedRouteRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppJoinCodeRoute: AppJoinCodeRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ClubsRoute: ClubsRoute,
  DrillsRoute: DrillsRoute,
  TournamentsRoute: TournamentsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
