-- =============================================
-- Spanish club directory seed
-- =============================================
--
-- 127 federated billiards clubs, so that /clubs and its map are a
-- directory rather than an empty page. Generated by scripts/es-clubs.mjs on
-- 2026-09-02 — do not hand-edit this file, edit the script and re-run it.
--
-- Every club here is either on a federation's own published roster, or is a
-- venue that hosted a tournament one of them ran:
--   Federació Catalana de Billar
--     https://fcbillar.cat/federacio/llistat-de-clubs-federacio-catalana-de-billar/
--   Federación Madrileña de Billar
--     https://www.federacionmadriddebillar.com/clubes/
--   Federación Andaluza de Billar — direcciones de contacto de clubes
--     https://fab.es/2015-16/Liga/Direcciones%20de%20contactos%20clubes.pdf
--   Federació de Billar de la Comunitat Valenciana — Listado de Clubs
--     https://www.fbillarcv.org/wp-content/uploads/2020/12/Listado-de-Clubs-FBCV.xlsx
--   Real Federación Española de Billar — organigrama
--     https://rfeb.org/organigrama.php?idx=16
--   Cuescore — venues of Spanish federation tournaments
--     https://api.cuescore.com/
--
-- Names, addresses and phone numbers are transcribed from those pages; nothing
-- is invented. Coordinates are geocoded from the address through Photon, which
-- is OpenStreetMap data under ODbL — the directory page carries the credit. A
-- club whose address would not geocode is present without coordinates rather
-- than with guessed ones, so it lists but does not pin.
--
-- Two things the rosters publish are deliberately not here: officers' mobile
-- numbers and the home addresses some small clubs use as their contact address.
-- Those are personal data about named individuals, and a public directory is
-- the wrong place for them. See scripts/es-clubs.sources.json.
--
-- Ownership: every club belongs to admin@poolclubs.app, which must have
-- signed in to the app at least once so that it has an auth.users row —
-- clubs.owner_id is NOT NULL and FK'd there. That account is also the marker
-- for "imported": DELETE FROM clubs WHERE owner_id = <that account> undoes the
-- whole seed, and the ON CONFLICT below refuses to touch a club owned by
-- anybody else, so a re-run can never overwrite a real club that has taken one
-- of these slugs.
--
-- The clubs have no members, no games and no logo. They are directory entries
-- waiting to be claimed, and they sort below any club with members.
--
-- The owner does get a players row in each, flagged is_caretaker: owning a club
-- is not enough to open it in the app, and the flag keeps that row out of
-- member_count and out of the roster. Apply sql/players-caretaker.sql first —
-- without that column this seed will not run.
--
-- Apply with `npm run db:sql sql/clubs-seed-es.sql`. That runs against the
-- LINKED project. To rehearse it, copy the file with the final COMMIT changed
-- to ROLLBACK and run that first: every CHECK and trigger fires and nothing
-- persists.
-- =============================================

BEGIN;

DO $seed$
DECLARE
  v_owner_email text := 'admin@poolclubs.app';
  v_owner_uuid  uuid;
  v_person_id   bigint;
  v_inserted    integer;
  v_joined      integer;
BEGIN
  SELECT id INTO v_owner_uuid FROM auth.users WHERE email = v_owner_email;
  IF v_owner_uuid IS NULL THEN
    RAISE EXCEPTION 'No auth.users row for %. Sign that account in to the app once, then re-run.', v_owner_email;
  END IF;

  -- One person per account, shared across every club — the same rule create_club
  -- follows. The owner has signed in, so this row almost always exists already.
  SELECT id INTO v_person_id FROM people WHERE user_id = v_owner_uuid;
  IF v_person_id IS NULL THEN
    INSERT INTO people (name, user_id) VALUES ('Admin', v_owner_uuid)
    RETURNING id INTO v_person_id;
  END IF;

  WITH seed(name, slug, address, city, lat, lon, phone, theme_color, timezone) AS (
    VALUES
    ('B.C. Granollers', 'b-c-granollers', 'Carrer Girona, 222', 'Granollers', 41.606114, 2.300811, NULL, 'purple', 'Europe/Madrid'),
    ('B. La Unió Coral', 'b-la-unio-coral', 'Passeig Bertrand, 13', 'Sant Feliu de Llobregat', 41.381881, 2.047833, '+34936661138', 'blue', 'Europe/Madrid'),
    ('Billar El Masnou', 'billar-el-masnou', 'Carrer Capità Mirambell, 28', 'El Masnou', 41.481461, 2.325567, '+34935403754', 'green', 'Europe/Madrid'),
    ('C.B. Borges', 'c-b-borges', 'Carrer Catalunya s/n, Pavelló Esportiu Francesc Macià', 'Les Borges Blanques', NULL, NULL, NULL, 'orange', 'Europe/Madrid'),
    ('C.B. 2000 Cerdanyola', 'c-b-2000-cerdanyola', 'Avinguda Guiera, 6', 'Cerdanyola del Vallès', 41.484424, 2.139044, '+34930427558', 'black', 'Europe/Madrid'),
    ('C.B. Alba', 'c-b-alba', 'Carrer Sant Pau, 13', 'Badalona', 41.452163, 2.250062, '+34933843405', 'maroon', 'Europe/Madrid'),
    ('C.B. Banyoles', 'c-b-banyoles', 'Carrer Abeurador, 10', 'Banyoles', 42.118283, 2.7643, NULL, 'blue', 'Europe/Madrid'),
    ('C.B. Barcelona', 'c-b-barcelona', 'Gran Via de les Corts Catalanes, 595-599', 'Barcelona', 41.388166, 2.166166, '+34933173641', 'black', 'Europe/Madrid'),
    ('C.B. Blanes', 'c-b-blanes', 'Plaça d''Espanya, 5', 'Blanes', 41.674389, 2.792543, '+34972337152', 'blue', 'Europe/Madrid'),
    ('C.B. Canet de Mar', 'c-b-canet-de-mar', 'Rial de Can Godany s/n', 'Canet de Mar', 41.590825, 2.59522, NULL, 'orange', 'Europe/Madrid'),
    ('C.B. Cardona', 'c-b-cardona', 'Carrer Generalitat, 1', 'Cardona', 41.914276, 1.68133, NULL, 'maroon', 'Europe/Madrid'),
    ('C.B. Lleida', 'c-b-lleida', 'Avinguda Navarra s/n, Camp d''Esports', 'Lleida', 41.621296, 0.61557, NULL, 'green', 'Europe/Madrid'),
    ('C.B. Lliçà d''Amunt', 'c-b-llica-damunt', 'Carrer Folch i Torres, 117', 'Lliçà d''Amunt', 41.613564, 2.238976, NULL, 'green', 'Europe/Madrid'),
    ('C.B. Llinars', 'c-b-llinars', 'Carrer Ravalet, 17', 'Llinars del Vallès', 41.642214, 2.409774, NULL, 'blue', 'Europe/Madrid'),
    ('C.B. Manresa', 'c-b-manresa', 'Passatge Dipòsits Vells, 4', 'Manresa', 41.732323, 1.831062, '+34938736051', 'black', 'Europe/Madrid'),
    ('C.B. Matadepera', 'c-b-matadepera', 'Carrer Pompeu Fabra s/n, Club de Golf Can Vinyers', 'Matadepera', 41.601231, 2.02752, NULL, 'red', 'Europe/Madrid'),
    ('C.B. Mataró', 'c-b-mataro', 'Passeig Carles Padrós, 12', 'Mataró', 41.547195, 2.441904, '+34937964557', 'red', 'Europe/Madrid'),
    ('C.B. Mollet', 'c-b-mollet', 'Ronda Can Fàbregas, 1', 'Mollet del Vallès', 41.535969, 2.219184, NULL, 'green', 'Europe/Madrid'),
    ('C.B. Monforte', 'c-b-monforte', 'Carrer Sant Antoni Maria Claret, 373', 'Barcelona', 41.421269, 2.18767, '+34933181019', 'red', 'Europe/Madrid'),
    ('C.B. Mont-roig', 'c-b-mont-roig', 'Carrer Vinyols, 17', 'Mont-roig del Camp', 41.087307, 0.961368, NULL, 'orange', 'Europe/Madrid'),
    ('C.B. Olesa', 'c-b-olesa', 'Plaça Països Catalans, 2', 'Olesa de Montserrat', 41.539684, 1.897969, '+34937082202', 'red', 'Europe/Madrid'),
    ('C.B. Prat', 'c-b-prat', 'Carrer Lo Gaiter del Llobregat, 24', 'El Prat de Llobregat', 41.328317, 2.095631, NULL, 'blue', 'Europe/Madrid'),
    ('C.B. Premià', 'c-b-premia', 'Carrer Sant Antoni, 60', 'Premià de Mar', 41.489787, 2.357972, NULL, 'maroon', 'Europe/Madrid'),
    ('C.B. Punt d''Atac', 'c-b-punt-datac', 'Carrer Capella, 6', 'Torredembarra', 41.143116, 1.400743, NULL, 'purple', 'Europe/Madrid'),
    ('C.B. Sant Adrià', 'c-b-sant-adria', 'Carrer Dr. Barraquer, 6', 'Sant Adrià de Besòs', 41.430011, 2.217227, '+34933814898', 'red', 'Europe/Madrid'),
    ('C.B. Sant Boi', 'c-b-sant-boi', 'Carrer Jaume I, 52', 'Sant Boi de Llobregat', 41.344562, 2.040307, NULL, 'black', 'Europe/Madrid'),
    ('C.B. Sant Feliu', 'c-b-sant-feliu', 'Centre Cívic', 'Sant Feliu de Codines', 41.687975, 2.162476, NULL, 'orange', 'Europe/Madrid'),
    ('C.B. Sants', 'c-b-sants', 'Carrer Rector Triadó, 53', 'Barcelona', 41.377645, 2.141859, NULL, 'purple', 'Europe/Madrid'),
    ('C.B. Tarragona', 'c-b-tarragona', 'Plaça Imperial Tarraco, 1, Estació d''Autobusos', 'Tarragona', 41.119321, 1.246347, '+34977227795', 'purple', 'Europe/Madrid'),
    ('C.B. Vic', 'c-b-vic', 'Carrer Arquebisbe Alemany, 24', 'Vic', 41.931954, 2.25164, NULL, 'orange', 'Europe/Madrid'),
    ('C.B. Vilanova', 'c-b-vilanova', 'Carrer Olesa s/n, Pavelló Plaça de les Casernes', 'Vilanova i la Geltrú', NULL, NULL, NULL, 'yellow', 'Europe/Madrid'),
    ('S.B. GEiEG', 's-b-geieg', 'Carrer Església de Sant Miquel, 18', 'Girona', 41.957761, 2.827642, NULL, 'blue', 'Europe/Madrid'),
    ('S.B. Coral Colón', 's-b-coral-colon', 'Avinguda Onze de Setembre, 125', 'Sabadell', 41.553421, 2.104422, NULL, 'black', 'Europe/Madrid'),
    ('S.B. Esplugues L''Avenç', 's-b-esplugues-lavenc', 'Carrer Àngel Guimerà, 27', 'Esplugues de Llobregat', 41.377154, 2.085711, '+34935135445', 'purple', 'Europe/Madrid'),
    ('S.B. Foment Molins', 's-b-foment-molins', 'Passeig del Terraplè, 49', 'Molins de Rei', 41.418608, 2.010665, NULL, 'maroon', 'Europe/Madrid'),
    ('S.B. La Gran Penya', 's-b-la-gran-penya', 'Rambla Principal, 52', 'Vilanova i la Geltrú', 41.223777, 1.724837, NULL, 'yellow', 'Europe/Madrid'),
    ('S.B. P.E. Centelles', 's-b-p-e-centelles', 'Carrer Sant Joan, 14', 'Centelles', 41.795481, 2.219196, NULL, 'red', 'Europe/Madrid'),
    ('S.E. Casal Cervera', 's-e-casal-cervera', 'Plaça Santa Anna, 2', 'Cervera', 41.669546, 1.271928, NULL, 'yellow', 'Europe/Madrid'),
    ('Alcalá Billar Club', 'alcala-billar-club', 'Paseo Nuestra Señora del Val, 4, Polideportivo Virgen del Val', 'Alcalá de Henares', NULL, NULL, NULL, 'purple', 'Europe/Madrid'),
    ('Club Billar Alcántara', 'club-billar-alcantara', 'Calle Alcántara, 48', 'Madrid', 40.431109, -3.673578, '+34914024079', 'orange', 'Europe/Madrid'),
    ('A.D.D. Billar Alcobendas', 'a-d-d-billar-alcobendas', 'Calle Cáceres s/n, Casa de las Asociaciones', 'Alcobendas', 40.540008, -3.635849, '+34916511797', 'red', 'Europe/Madrid'),
    ('Black Ball Madrid', 'black-ball-madrid', 'Calle Luis I, 86', 'Madrid', 40.392272, -3.668534, '+34910141339', 'maroon', 'Europe/Madrid'),
    ('Peña Billarística Bellas Artes', 'pena-billaristica-bellas-artes', 'Calle Alcalá, 42', 'Madrid', 40.418207, -3.696514, NULL, 'purple', 'Europe/Madrid'),
    ('Club Billar Getafe', 'club-billar-getafe', 'Avenida Juan de Borbón s/n, Polideportivo Juan de la Cierva', 'Getafe', 40.319157, -3.71656, NULL, 'black', 'Europe/Madrid'),
    ('Club Billar Iberia', 'club-billar-iberia', 'Calle Núñez de Balboa, 115', 'Madrid', 40.432642, -3.679555, NULL, 'purple', 'Europe/Madrid'),
    ('Club Billar Kalima-Rivas Vaciamadrid', 'club-billar-kalima-rivas-vaciamadrid', 'Calle Mirador s/n, Polideportivo Parque del Sureste', 'Rivas-Vaciamadrid', 40.323915, -3.511297, NULL, 'yellow', 'Europe/Madrid'),
    ('Madrid Escuela Nacional', 'madrid-escuela-nacional', 'Calle Alcántara, 48', 'Madrid', 40.431109, -3.673578, '+34914024079', 'black', 'Europe/Madrid'),
    ('Club Billar Magerit', 'club-billar-magerit', 'Calle Payaso Fofó, 1', 'Madrid', 40.387218, -3.660587, '+34915545956', 'maroon', 'Europe/Madrid'),
    ('Club Billar Móstoles', 'club-billar-mostoles', 'Calle Libertad, 36-38, C.C. Ecomóstoles', 'Móstoles', 40.325819, -3.853744, NULL, 'purple', 'Europe/Madrid'),
    ('Club Billar Perales del Río', 'club-billar-perales-del-rio', 'Calle Juan de Mairena s/n, Centro Cultural Julián Marías', 'Getafe', NULL, NULL, NULL, 'red', 'Europe/Madrid'),
    ('Amigos Billar Real Casino', 'amigos-billar-real-casino', 'Calle Aduana, 10', 'Madrid', 40.418347, -3.7011, NULL, 'black', 'Europe/Madrid'),
    ('Snooker Madrid', 'snooker-madrid', 'Carretera de Fuencarral, 74', 'Alcobendas', 40.527397, -3.652989, NULL, 'orange', 'Europe/Madrid'),
    ('Snooker Valdelasfuentes', 'snooker-valdelasfuentes', 'Avenida Miguel de Cervantes s/n, Ciudad Deportiva Valdelasfuentes', 'Alcobendas', 40.553355, -3.65187, NULL, 'black', 'Europe/Madrid'),
    ('Tilt Billiard Club', 'tilt-billiard-club', 'Paseo de Santa María de la Cabeza, 75', 'Madrid', 40.398554, -3.701077, '+34914744424', 'blue', 'Europe/Madrid'),
    ('Club Billar Vallecas', 'club-billar-vallecas', 'Calle Játiva, 12', 'Madrid', 40.397649, -3.672085, NULL, 'yellow', 'Europe/Madrid'),
    ('Club Billar Billardo', 'club-billar-billardo', 'Calle San Bernardo, 22', 'Madrid', 40.423004, -3.707431, NULL, 'yellow', 'Europe/Madrid'),
    ('Club de Billar Bollullos', 'club-de-billar-bollullos', 'Polideportivo Municipal, Calle Nerva s/n', 'Bollullos del Condado', 37.340409, -6.533825, '+34959412730', 'purple', 'Europe/Madrid'),
    ('Club de Billar Sevilla', 'club-de-billar-sevilla', 'Calle Duque de Rivas, 27 bajo', 'Sevilla', 37.382343, -5.96305, '+34954769579', 'purple', 'Europe/Madrid'),
    ('Asociación Cordobesa de Billar', 'asociacion-cordobesa-de-billar', 'Calle Los Metalúrgicos, Nave 41, Polígono Industrial Pedroches', 'Córdoba', NULL, NULL, '+34957438218', 'maroon', 'Europe/Madrid'),
    ('Club de Billar Urso', 'club-de-billar-urso', 'Casino de Osuna', 'Osuna', 37.237426, -5.102856, '+34954810519', 'red', 'Europe/Madrid'),
    ('Club de Billar La Palma', 'club-de-billar-la-palma', 'Casa de la Juventud, Plaza del Punto s/n', 'La Palma del Condado', NULL, NULL, NULL, 'yellow', 'Europe/Madrid'),
    ('Club de Billar Alcalá', 'club-de-billar-alcala', 'Calle Oviedo, 7', 'Alcalá de Guadaíra', 37.333948, -5.834969, '+34955686372', 'black', 'Europe/Madrid'),
    ('Club de Billar Almonte', 'club-de-billar-almonte', 'Calle El Cerro, 2, Casino La Paz', 'Almonte', NULL, NULL, '+34959407934', 'blue', 'Europe/Madrid'),
    ('C.B. Elio Antonio', 'c-b-elio-antonio', 'Avenida Océano Atlántico s/n', 'Lebrija', 36.92626, -6.072333, NULL, 'yellow', 'Europe/Madrid'),
    ('Club de Billar Casino Artesanos', 'club-de-billar-casino-artesanos', 'Calle Cánovas del Castillo, 1', 'Écija', 37.538656, -5.079872, '+34954831038', 'purple', 'Europe/Madrid'),
    ('C.B. Los Amigos', 'c-b-los-amigos', 'Polígono Los Cerros, parcela 127', 'Úbeda', NULL, NULL, NULL, 'black', 'Europe/Madrid'),
    ('C.B. Fuengirola', 'c-b-fuengirola', 'Avenida Jesús Santos Reim, Edificio Vega II bajo', 'Fuengirola', 36.54181, -4.623976, NULL, 'yellow', 'Europe/Madrid'),
    ('Club de Billar Valencia', 'club-de-billar-valencia', 'Calle Reina, 68 (Edificio Ateneo Mar)', 'Valencia', 39.466622, -0.328861, '+34625502137', 'red', 'Europe/Madrid'),
    ('Club de Billar Ateneo Mercantil de Valencia', 'club-de-billar-ateneo-mercantil-de-valencia', 'Plaza del Ayuntamiento, 18', 'Valencia', 39.470886, -0.376243, '+34963521612', 'purple', 'Europe/Madrid'),
    ('Club de Billar Sindicato Agrícola de Puçol', 'club-de-billar-sindicato-agricola-de-pucol', 'Calle San Juan, 93', 'Puçol', 39.617024, -0.304897, NULL, 'maroon', 'Europe/Madrid'),
    ('Club de Billar Paiporta', 'club-de-billar-paiporta', 'Plaza Iglesia San Jorge, 7 bajo', 'Paiporta', NULL, NULL, '+34963972321', 'blue', 'Europe/Madrid'),
    ('Club de Billar Sueca', 'club-de-billar-sueca', 'Ronda País Valencià s/n', 'Sueca', 39.199823, -0.308834, '+34630810638', 'yellow', 'Europe/Madrid'),
    ('Club de Billar Almussafes', 'club-de-billar-almussafes', 'Calle Poliesportiu s/n', 'Almussafes', 39.294866, -0.414345, '+34961794136', 'black', 'Europe/Madrid'),
    ('Club de Billar Llíria', 'club-de-billar-lliria', 'Calle Nuestra Señora de Montiel, 7', 'Llíria', NULL, NULL, '+34646479212', 'red', 'Europe/Madrid'),
    ('Club de Billar La Mutua de Chiva', 'club-de-billar-la-mutua-de-chiva', 'Calle Antonio Machado, 6', 'Chiva', 39.472714, -0.718654, '+34633621186', 'black', 'Europe/Madrid'),
    ('Gandia Billar Club', 'gandia-billar-club', 'Calle Miramar, 13', 'Gandia', NULL, NULL, '+34962043599', 'green', 'Europe/Madrid'),
    ('Club de Billar L''Alcúdia', 'club-de-billar-lalcudia', NULL, 'L''Alcúdia', 39.19471, -0.504241, '+34690180280', 'orange', 'Europe/Madrid'),
    ('Club Billar Villalonga', 'club-billar-villalonga', 'Avenida Lorcha, 4', 'Villalonga', 38.885531, -0.212454, NULL, 'orange', 'Europe/Madrid'),
    ('Club de Billar Alzira', 'club-de-billar-alzira', 'Ronda Barrablet, 29 A', 'Alzira', 39.158968, -0.445197, '+34962955133', 'red', 'Europe/Madrid'),
    ('Club de Billar Vinalesa', 'club-de-billar-vinalesa', 'Plaza Castell, 2', 'Vinalesa', 39.535877, -0.370945, NULL, 'maroon', 'Europe/Madrid'),
    ('Club Billar Montcada', 'club-billar-montcada', 'Calle Lluís Vives, 18', 'Moncada', NULL, NULL, '+34961300019', 'yellow', 'Europe/Madrid'),
    ('Club de Billar Torrent', 'club-de-billar-torrent', 'Calle Marco, 1', 'Torrent', NULL, NULL, '+34961293179', 'black', 'Europe/Madrid'),
    ('Mislata Club Billar', 'mislata-club-billar', 'Calle Doctor Fleming, 12', 'Mislata', 39.477379, -0.415836, '+34961848058', 'orange', 'Europe/Madrid'),
    ('Club de Billar Bocairent', 'club-de-billar-bocairent', 'Avenida Diputat Castelló, 15', 'Bocairent', NULL, NULL, NULL, 'maroon', 'Europe/Madrid'),
    ('Alicante Billar Club', 'alicante-billar-club', 'Calle Devesa, 4', 'Alicante', 38.359389, -0.484461, '+34965241927', 'yellow', 'Europe/Madrid'),
    ('Club de Billar David Betis Florida', 'club-de-billar-david-betis-florida', 'Calle Grado, 8', 'Alicante', 38.344252, -0.510409, '+34966085051', 'blue', 'Europe/Madrid'),
    ('Club de Billar C.E.E. Idella', 'club-de-billar-c-e-e-idella', 'Avenida del Centro Excursionista Eldense s/n', 'Elda', 38.46797, -0.808493, '+34965385567', 'red', 'Europe/Madrid'),
    ('Elx Billar Club', 'elx-billar-club', 'Calle Monóvar, 60', 'Elche', NULL, NULL, NULL, 'yellow', 'Europe/Madrid'),
    ('Club de Billar José Pérez Ruiz de Callosa', 'club-de-billar-jose-perez-ruiz-de-callosa', 'Plaza de la Navidad s/n (Casa de la Juventud)', 'Callosa de Segura', NULL, NULL, NULL, 'orange', 'Europe/Madrid'),
    ('Club de Billar Alcoy', 'club-de-billar-alcoy', NULL, 'Alcoy', NULL, NULL, NULL, 'blue', 'Europe/Madrid'),
    ('Club de Billar Casino de Monóvar', 'club-de-billar-casino-de-monovar', 'Calle San Juan, 13', 'Monóvar', NULL, NULL, '+34965470090', 'black', 'Europe/Madrid'),
    ('Club Billar Torrevieja', 'club-billar-torrevieja', 'Polideportivo Cecilio Gallego', 'Torrevieja', 38.00515, -0.668852, '+34965713701', 'orange', 'Europe/Madrid'),
    ('Club Billar Onil', 'club-billar-onil', 'Avenida Constitución', 'Onil', 38.628872, -0.666048, '+34686226582', 'black', 'Europe/Madrid'),
    ('Club de Billar C.A.M. Villenense', 'club-de-billar-c-a-m-villenense', 'Casa Cabanes, Las Fuentes, 20', 'Villena', 38.651213, -0.884532, '+34965800334', 'maroon', 'Europe/Madrid'),
    ('Club de Billar Castalla', 'club-de-billar-castalla', 'Polideportivo Municipal', 'Castalla', NULL, NULL, '+34649442174', 'yellow', 'Europe/Madrid'),
    ('Club de Billar Casino El Campello', 'club-de-billar-casino-el-campello', 'Plaza Constitución', 'El Campello', 38.429137, -0.397919, '+34666467547', 'red', 'Europe/Madrid'),
    ('Novelda Billar Club', 'novelda-billar-club', 'Plaza Santos Médicos s/n', 'Novelda', 38.386243, -0.765747, '+34652355502', 'yellow', 'Europe/Madrid'),
    ('B.C. Benidorm', 'b-c-benidorm', 'Palacio de Deportes, Partida Salto del Agua s/n', 'Benidorm', 38.540625, -0.129093, '+34652917319', 'yellow', 'Europe/Madrid'),
    ('Club de Billar Castellón', 'club-de-billar-castellon', 'Plaza Puerta del Sol, 1', 'Castellón de la Plana', 39.984486, -0.038916, '+34964223500', 'orange', 'Europe/Madrid'),
    ('Club de Billar Betxí', 'club-de-billar-betxi', 'Calle Pius XII, 47', 'Betxí', 39.930188, -0.200916, NULL, 'blue', 'Europe/Madrid'),
    ('Club Billar La Vall', 'club-billar-la-vall', 'Barrio Carmaday s/n', 'La Vall d''Uixó', 39.80856, -0.22479, NULL, 'maroon', 'Europe/Madrid'),
    ('CB. Círculo Mercantil', 'cb-circulo-mercantil', 'Calle Echegaray, 1', 'Castellón de la Plana', 39.98697, -0.041348, NULL, 'maroon', 'Europe/Madrid'),
    ('C.D. OrpesaPool', 'c-d-orpesapool', 'Calle Francisco Sevillano, 49', 'Oropesa del Mar', 40.092033, 0.13602, '+34653976979', 'orange', 'Europe/Madrid'),
    ('Club Billar Casino de Cartagena', 'club-billar-casino-de-cartagena', NULL, 'Cartagena', NULL, NULL, NULL, 'blue', 'Europe/Madrid'),
    ('Club Billar Maracena', 'club-billar-maracena', NULL, 'Maracena', NULL, NULL, NULL, 'green', 'Europe/Madrid'),
    ('Club Billar Murcia', 'club-billar-murcia', NULL, 'Murcia', NULL, NULL, NULL, 'maroon', 'Europe/Madrid'),
    ('Club Billar Valladolid', 'club-billar-valladolid', NULL, 'Valladolid', NULL, NULL, NULL, 'purple', 'Europe/Madrid'),
    ('Billiard School Club 2021', 'billiard-school-club-2021', 'c/Peru, 36 Pol.Ind.Villares de la Reina', 'Villares de la Reina', 40.996292, -5.634214, NULL, 'yellow', 'Europe/Madrid'),
    ('Break&Run', 'break-run', 'Polig. Ind. de Naón, Urb. Monsagre, Nave 5, 33429 Granda, Siero', 'Siero', NULL, NULL, NULL, 'maroon', 'Europe/Madrid'),
    ('Club Billar Pool Denia y la Marina Alta', 'club-billar-pool-denia-y-la-marina-alta', 'Partida Madrigueres Nord A-59', 'Denia', NULL, NULL, NULL, 'black', 'Europe/Madrid'),
    ('Club Billar Snooker Valencia', 'club-billar-snooker-valencia', 'Sedaví', 'Sedaví', 39.424587, -0.379862, NULL, 'maroon', 'Europe/Madrid'),
    ('Club Billar Teo', 'club-billar-teo', 'Rúa Carballo, 3', 'Os Tilos', 42.846483, -8.540696, NULL, 'blue', 'Europe/Madrid'),
    ('Club De Billar Adai', 'club-de-billar-adai', 'Adai', 'Lugo', 43.022627, -7.60202, NULL, 'orange', 'Europe/Madrid'),
    ('Club de billar Estepona', 'club-de-billar-estepona', 'Estepona', 'Estepona', 36.423218, -5.153318, NULL, 'red', 'Europe/Madrid'),
    ('Club Rías Baixas', 'club-rias-baixas', 'Lugar da Igrexa N19, Rua Ponte Dena', 'Pontevedra', NULL, NULL, NULL, 'orange', 'Europe/Madrid'),
    ('Club Sierra Billiard''s Valencia Pool', 'club-sierra-billiards-valencia-pool', 'Carrer Riu Vinalopó 50', 'Valencia', NULL, NULL, NULL, 'red', 'Europe/Madrid'),
    ('Lo de Eva (Pool & Food)', 'lo-de-eva-pool-food', 'Avinguda Pla de Messell 2', 'Campello', 38.445747, -0.380676, NULL, 'blue', 'Europe/Madrid'),
    ('Origen R', 'origen-r', 'Av. Diputación, 56', 'Calpe', 38.646365, 0.046137, NULL, 'maroon', 'Europe/Madrid'),
    ('Panda Pool Madrid (Sede)', 'panda-pool-madrid-sede', 'Cam. de las hormigueras 122 BIS, 2ª Q1', 'Madrid', NULL, NULL, NULL, 'orange', 'Europe/Madrid'),
    ('Pool Pontevedra', 'pool-pontevedra', 'Camiño Liñares, 21', 'Poio', 42.44217, -8.673998, NULL, 'maroon', 'Europe/Madrid'),
    ('Sala Quince. Salón de Billar +Pool', 'sala-quince-salon-de-billar-pool', 'Federico Olmeda 15', 'Burgos', 42.349759, -3.692105, NULL, 'orange', 'Europe/Madrid'),
    ('Straight Pool DENIA', 'straight-pool-denia', 'DENIA', 'Denia', 38.840838, 0.10611, NULL, 'yellow', 'Europe/Madrid'),
    ('TECNO POOL Hotel LAKUA', 'tecno-pool-hotel-lakua', 'tarragona, 8', 'Vitoria', 42.869024, -2.689506, NULL, 'blue', 'Europe/Madrid'),
    ('Val Miñor Pool', 'val-minor-pool', 'Rua Eduardo Iglesias 30, Bajo', 'Gondomar', 42.113363, -8.760654, NULL, 'black', 'Europe/Madrid'),
    ('Val Miñor Pool', 'val-minor-pool-pontevedra', 'Rúa Eduardo Iglesias, 30, Bajo, Gondomar', 'Pontevedra', NULL, NULL, NULL, 'red', 'Europe/Madrid'),
    ('X-united Sevilla', 'x-united-sevilla', 'Calle Pedro Muñoz Torres 3', 'Sevilla', 37.369531, -5.960839, NULL, 'maroon', 'Europe/Madrid'),
    ('X-united Store', 'x-united-store', 'C. Gramil, 19-9', 'Sevilla', 37.410272, -5.959356, NULL, 'purple', 'Europe/Madrid')
  ), upserted AS (
    INSERT INTO clubs (name, slug, owner_id, is_public, address, city, country, lat, lon, phone, theme_color, timezone)
    SELECT s.name, s.slug, v_owner_uuid, true, s.address, s.city, 'ES',
           s.lat::double precision, s.lon::double precision, s.phone,
           s.theme_color::"BallColor", s.timezone
    FROM seed s
    ON CONFLICT (slug) DO UPDATE SET
      name = EXCLUDED.name,
      address = EXCLUDED.address,
      city = EXCLUDED.city,
      lat = EXCLUDED.lat,
      lon = EXCLUDED.lon,
      phone = EXCLUDED.phone
    -- Only ever updates a row this seed owns. A club somebody has since made
    -- their own keeps its slug and everything else.
    WHERE clubs.owner_id = v_owner_uuid
    RETURNING id
  ), joined AS (
    -- Owning a club does not open it: the app resolves a club from your
    -- memberships, so without this row the owner cannot reach a single one of
    -- these clubs in the app, nor see them in the club switcher.
    --
    -- is_caretaker is what keeps that honest — the row grants the keys without
    -- counting as a member, so a club nobody has joined still reads as empty in
    -- the directory. See sql/players-caretaker.sql.
    INSERT INTO players (club_id, person_id, category, status, is_caretaker)
    SELECT u.id, v_person_id, 3, 'active', true
    FROM upserted u
    ON CONFLICT (club_id, person_id) DO UPDATE
      SET status = 'active', is_caretaker = true
    RETURNING 1
  )
  SELECT
    (SELECT count(*) FROM upserted),
    (SELECT count(*) FROM joined)
  INTO v_inserted, v_joined;

  RAISE NOTICE 'Spanish club seed: % of % clubs written, % caretaker memberships, owner %',
    v_inserted, 127, v_joined, v_owner_email;
END
$seed$;

COMMIT;
