-- The club night: a match in progress, the tables it happens on, who is in the
-- room, and who is waiting for a table.
--
-- Apply with `npm run db:sql sql/live-night.sql`, then
-- `npm run db:dump && npm run db:types`.
--
-- Two new tables and four columns on `players`. Check-in and the queue are
-- membership state, not tables of their own: `players` already is "this person,
-- in this club", it is already in the realtime publication, and it is already
-- invalidated as one key — so they cost no policy, no listener and no cache key.

-- ---------------------------------------------------------------------------
-- The venue's tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.club_tables (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id    integer NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
    label      text NOT NULL,
    -- Ordering by label puts "10" before "2", and ordering by id breaks the
    -- first time a table is retired and re-added. This is the one thing a wall
    -- display gets visibly wrong.
    sort_order smallint NOT NULL DEFAULT 0,
    CONSTRAINT club_tables_label_check
        CHECK (char_length(btrim(label)) BETWEEN 1 AND 24)
);

CREATE UNIQUE INDEX IF NOT EXISTS club_tables_label_key
    ON public.club_tables (club_id, lower(btrim(label)));
CREATE INDEX IF NOT EXISTS club_tables_club_idx
    ON public.club_tables (club_id, sort_order);

-- No `is_active`: nothing durable points at a table — `games` deliberately does
-- not carry one — so retiring a table is a DELETE.

-- ---------------------------------------------------------------------------
-- The match in progress
-- ---------------------------------------------------------------------------

-- No status column and no finished_at. The row's existence is the status:
-- live = the row is here, finished = it is gone and a `games` row is not,
-- abandoned = it is here and nobody has touched it in ABANDON_AFTER (3h).
CREATE TABLE IF NOT EXISTS public.live_matches (
    -- Generated by the client, the way tournament_matches ids are (see
    -- src/libs/bracket.ts): the optimistic row and the row that comes back over
    -- the socket then share an id, and the cache reconciles them by identity.
    id       uuid PRIMARY KEY,
    club_id  integer NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
    -- Nullable: a match on no table is a real thing in a busy club.
    table_id integer REFERENCES public.club_tables(id) ON DELETE CASCADE,

    -- The same four seats as `games`, with the same nullability rules, so
    -- finishing is a straight copy.
    player_1_id  bigint NOT NULL REFERENCES public.players(id) ON DELETE CASCADE,
    player_2_id  bigint NOT NULL REFERENCES public.players(id) ON DELETE CASCADE,
    player_1b_id bigint REFERENCES public.players(id) ON DELETE CASCADE,
    player_2b_id bigint REFERENCES public.players(id) ON DELETE CASCADE,

    mode       public."GameMode"   NOT NULL DEFAULT 'single',
    discipline public."Discipline" NOT NULL DEFAULT '9ball',

    player_1_score smallint NOT NULL DEFAULT 0,
    player_2_score smallint NOT NULL DEFAULT 0,
    race_to        smallint NOT NULL DEFAULT 5,

    -- Which side scored last, 1 or 2. Undo cannot be built from two counters:
    -- without this, undo on the other phone decrements the wrong player.
    last_side smallint,

    -- Where this match came from, so finishing can close it out. At most one.
    challenge_id        integer REFERENCES public.challenges(id) ON DELETE SET NULL,
    tournament_match_id uuid REFERENCES public.tournament_matches(id) ON DELETE SET NULL,

    started_at timestamptz NOT NULL DEFAULT now(),
    -- Maintained by live_match_guard, never by the client: this is the
    -- abandonment clock.
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT live_matches_scores_check
        CHECK (player_1_score BETWEEN 0 AND 200 AND player_2_score BETWEEN 0 AND 200),
    CONSTRAINT live_matches_race_check CHECK (race_to BETWEEN 1 AND 50),
    CONSTRAINT live_matches_last_side_check CHECK (last_side IS NULL OR last_side IN (1, 2)),
    CONSTRAINT live_matches_seats_check CHECK (player_1_id <> player_2_id),
    CONSTRAINT live_matches_doubles_check
        CHECK ((mode = 'doubles') = (player_1b_id IS NOT NULL AND player_2b_id IS NOT NULL)),
    CONSTRAINT live_matches_origin_check
        CHECK (num_nonnulls(challenge_id, tournament_match_id) <= 1)
);

-- One live match per table. This is also what makes an abandoned match block
-- its table, which is what puts someone in front of it who wants it cleared.
CREATE UNIQUE INDEX IF NOT EXISTS live_matches_one_per_table
    ON public.live_matches (table_id) WHERE table_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS live_matches_club_idx
    ON public.live_matches (club_id, updated_at DESC);

-- ---------------------------------------------------------------------------
-- Check-in and the queue: membership state
-- ---------------------------------------------------------------------------

ALTER TABLE public.players
    ADD COLUMN IF NOT EXISTS present_since   timestamptz,
    ADD COLUMN IF NOT EXISTS queued_table_id integer REFERENCES public.club_tables(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS queued_at       timestamptz,
    -- A device account: the tablet at the table. Set by the club owner only —
    -- see the guard amendment below, which is what stops a member granting
    -- themselves scoring rights over every match in the club.
    ADD COLUMN IF NOT EXISTS is_device       boolean NOT NULL DEFAULT false;

ALTER TABLE public.players DROP CONSTRAINT IF EXISTS players_queue_check;
ALTER TABLE public.players ADD CONSTRAINT players_queue_check
    CHECK ((queued_table_id IS NULL) = (queued_at IS NULL));

CREATE INDEX IF NOT EXISTS players_queue_idx
    ON public.players (queued_table_id, queued_at) WHERE queued_table_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Who may score
-- ---------------------------------------------------------------------------

-- The tablet at the table. A normal club member account, flagged, so it can
-- score a match it is not playing in and do nothing else it could not do
-- before.
CREATE OR REPLACE FUNCTION public.is_club_device(cid integer) RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  SELECT EXISTS (
    SELECT 1 FROM players p
    JOIN people pe ON pe.id = p.person_id
    WHERE p.club_id = cid AND pe.user_id = auth.uid()
      AND p.status = 'active' AND p.is_device
  );
$$;

-- Scalar arguments rather than a row, so the same call works in USING, in
-- WITH CHECK (where looking the row up by id would read the committed row, not
-- NEW) and inside finish_live_match, which has no RLS to lean on.
-- is_own_player takes integer and the seats are bigint, hence the casts.
CREATE OR REPLACE FUNCTION public.can_score_live_match(
    cid integer, p1 bigint, p2 bigint, p1b bigint, p2b bigint
) RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  -- is_own_player(NULL) is false, so the empty doubles seats need no guard.
  SELECT is_club_admin(cid)
      OR is_club_device(cid)
      OR is_own_player(p1::integer)
      OR is_own_player(p2::integer)
      OR is_own_player(p1b::integer)
      OR is_own_player(p2b::integer);
$$;

-- The UPDATE policy is broad enough to let a participant through; this is what
-- says which columns a participant may actually move. Same split as
-- tournament_match_guard.
CREATE OR REPLACE FUNCTION public.live_match_guard() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.table_id IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM club_tables WHERE id = NEW.table_id AND club_id = NEW.club_id
    ) THEN
      RAISE EXCEPTION 'that table belongs to another club';
    END IF;
    RETURN NEW;
  END IF;

  -- The abandonment clock is the server's, not the client's.
  NEW.updated_at := now();

  IF NEW.club_id IS DISTINCT FROM OLD.club_id THEN
    RAISE EXCEPTION 'a live match cannot change club';
  END IF;

  IF NEW.table_id IS DISTINCT FROM OLD.table_id AND NEW.table_id IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM club_tables WHERE id = NEW.table_id AND club_id = NEW.club_id
     ) THEN
    RAISE EXCEPTION 'that table belongs to another club';
  END IF;

  IF is_club_admin(OLD.club_id) OR is_club_device(OLD.club_id) THEN
    RETURN NEW;
  END IF;

  IF ROW(NEW.id, NEW.player_1_id, NEW.player_2_id, NEW.player_1b_id,
         NEW.player_2b_id, NEW.mode, NEW.challenge_id,
         NEW.tournament_match_id, NEW.started_at)
     IS DISTINCT FROM
     ROW(OLD.id, OLD.player_1_id, OLD.player_2_id, OLD.player_1b_id,
         OLD.player_2b_id, OLD.mode, OLD.challenge_id,
         OLD.tournament_match_id, OLD.started_at)
  THEN
    RAISE EXCEPTION 'players may change the score, the table, the race and the discipline';
  END IF;

  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS live_matches_guard ON public.live_matches;
CREATE TRIGGER live_matches_guard
    BEFORE INSERT OR UPDATE ON public.live_matches
    FOR EACH ROW EXECUTE FUNCTION public.live_match_guard();

-- ---------------------------------------------------------------------------
-- Finishing: one game row, one transaction
-- ---------------------------------------------------------------------------

-- Both phones and the tablet all show a Finish button on the same row, and
-- `games` has nothing to deduplicate on — two taps would file two results and
-- both would land in the Elo ranking. The row lock is the only defence.
CREATE OR REPLACE FUNCTION public.finish_live_match(p_id uuid) RETURNS uuid
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
  m public.live_matches;
  g uuid;
  w bigint;
BEGIN
  SELECT * INTO m FROM live_matches WHERE id = p_id FOR UPDATE;
  IF m.id IS NULL THEN
    RAISE EXCEPTION 'this match is already finished';
  END IF;

  -- SECURITY DEFINER bypasses RLS, so the policy's predicate is restated here
  -- by hand. Same function, so the two cannot drift.
  IF NOT can_score_live_match(m.club_id, m.player_1_id, m.player_2_id,
                              m.player_1b_id, m.player_2b_id) THEN
    RAISE EXCEPTION 'only the players or the club can finish this match';
  END IF;

  -- The daily table discards a tie as bad data, so it must not be filed at all.
  IF m.player_1_score = m.player_2_score THEN
    RAISE EXCEPTION 'a finished match needs a winner';
  END IF;

  INSERT INTO games (club_id, mode, discipline, played_at,
                     player_1_id, player_2_id, player_1b_id, player_2b_id,
                     player_1_score, player_2_score)
  VALUES (m.club_id, m.mode, m.discipline, now(),
          m.player_1_id, m.player_2_id, m.player_1b_id, m.player_2b_id,
          m.player_1_score, m.player_2_score)
  RETURNING id INTO g;

  IF m.challenge_id IS NOT NULL THEN
    UPDATE challenges SET status = 'played', game_id = g WHERE id = m.challenge_id;
  END IF;

  IF m.tournament_match_id IS NOT NULL THEN
    w := CASE WHEN m.player_1_score > m.player_2_score
              THEN m.player_1_id ELSE m.player_2_id END;
    -- tournament_match_guard still fires and permits exactly these two columns
    -- for a non-admin, which is the validation this would otherwise repeat.
    UPDATE tournament_matches SET game_id = g, winner_id = w
    WHERE id = m.tournament_match_id;
  END IF;

  DELETE FROM live_matches WHERE id = p_id;
  RETURN g;
END $$;

-- ALTER DEFAULT PRIVILEGES grants every function to anon, so this one has to be
-- taken back by hand — the same way create_club is.
REVOKE ALL ON FUNCTION public.finish_live_match(uuid) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.finish_live_match(uuid) TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- The is_device hole
-- ---------------------------------------------------------------------------

-- "Members can update club players" exists so the roster editor can set a
-- division, and it would also let any member set is_device on their own row and
-- take scoring rights over every match in the club. This clause is not
-- optional. The rest of the function is unchanged.
CREATE OR REPLACE FUNCTION public.players_guard_membership() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN NEW; END IF;

  IF NEW.club_id IS DISTINCT FROM OLD.club_id AND NOT is_club_admin(OLD.club_id) THEN
    RAISE EXCEPTION 'only the club owner may move a player between clubs';
  END IF;

  -- A membership never changes hands. Without this, "Members can update club
  -- players" — which exists so the roster editor can set a division — would also
  -- let a member point somebody else's membership at their own person.
  IF NEW.person_id IS DISTINCT FROM OLD.person_id THEN
    RAISE EXCEPTION 'a membership cannot be reassigned to another person';
  END IF;

  -- The one status change that is not the owner's: claiming an unclaimed person
  -- drops their memberships to 'pending'. join_club() relies on this.
  IF NEW.status IS DISTINCT FROM OLD.status
     AND NOT is_club_admin(OLD.club_id)
     AND NOT (
       NEW.status = 'pending'
       AND EXISTS (SELECT 1 FROM people WHERE id = NEW.person_id AND user_id = auth.uid())
     ) THEN
    RAISE EXCEPTION 'only the club owner may change a member''s status';
  END IF;

  -- A device account scores matches it is not in. Only the owner designates one.
  IF NEW.is_device IS DISTINCT FROM OLD.is_device AND NOT is_club_admin(OLD.club_id) THEN
    RAISE EXCEPTION 'only the club owner may designate a device account';
  END IF;

  -- You check yourself in and you queue yourself. The tablet does it for the
  -- person standing in front of it.
  IF (NEW.present_since, NEW.queued_table_id, NEW.queued_at)
     IS DISTINCT FROM (OLD.present_since, OLD.queued_table_id, OLD.queued_at)
     AND NOT (is_own_player(NEW.id::integer)
              OR is_club_admin(OLD.club_id)
              OR is_club_device(OLD.club_id)) THEN
    RAISE EXCEPTION 'you can only check yourself in';
  END IF;

  RETURN NEW;
END $$;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.club_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_matches ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.club_tables TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.live_matches TO anon, authenticated, service_role;

DROP POLICY IF EXISTS "Members can see the club's tables" ON public.club_tables;
CREATE POLICY "Members can see the club's tables" ON public.club_tables
    FOR SELECT TO authenticated USING (is_club_member(club_id));

DROP POLICY IF EXISTS "Tables of public clubs are readable by anyone" ON public.club_tables;
CREATE POLICY "Tables of public clubs are readable by anyone" ON public.club_tables
    FOR SELECT TO anon USING (is_public_club(club_id));

-- FOR ALL rather than a policy per verb: this table is admin-only to write and
-- three identical predicates would say nothing the one does not.
DROP POLICY IF EXISTS "Admin can manage tables" ON public.club_tables;
CREATE POLICY "Admin can manage tables" ON public.club_tables
    FOR ALL TO authenticated
    USING (is_club_admin(club_id)) WITH CHECK (is_club_admin(club_id));

DROP POLICY IF EXISTS "Members can watch live matches" ON public.live_matches;
CREATE POLICY "Members can watch live matches" ON public.live_matches
    FOR SELECT TO authenticated USING (is_club_member(club_id));

DROP POLICY IF EXISTS "Live matches of public clubs are readable by anyone" ON public.live_matches;
CREATE POLICY "Live matches of public clubs are readable by anyone" ON public.live_matches
    FOR SELECT TO anon USING (is_public_club(club_id));

-- Tighter than plain membership: you start a match you are in, or you are the
-- owner or the tablet.
DROP POLICY IF EXISTS "Members can start a live match" ON public.live_matches;
CREATE POLICY "Members can start a live match" ON public.live_matches
    FOR INSERT TO authenticated
    WITH CHECK (
      is_club_member(club_id)
      AND can_score_live_match(club_id, player_1_id, player_2_id, player_1b_id, player_2b_id)
    );

DROP POLICY IF EXISTS "Participants and the club can score" ON public.live_matches;
CREATE POLICY "Participants and the club can score" ON public.live_matches
    FOR UPDATE TO authenticated
    USING (can_score_live_match(club_id, player_1_id, player_2_id, player_1b_id, player_2b_id))
    WITH CHECK (can_score_live_match(club_id, player_1_id, player_2_id, player_1b_id, player_2b_id));

DROP POLICY IF EXISTS "Participants and the club can abandon" ON public.live_matches;
CREATE POLICY "Participants and the club can abandon" ON public.live_matches
    FOR DELETE TO authenticated
    USING (can_score_live_match(club_id, player_1_id, player_2_id, player_1b_id, player_2b_id));

-- OR'd with the one above. Two people start a match and go home; the row still
-- holds their table, so the next person standing at it is exactly who should be
-- able to clear it. Three hours — kept in step with ABANDON_AFTER_MS in
-- src/libs/night.ts, which is where the client copies of this rule live.
DROP POLICY IF EXISTS "Members can clear an abandoned match" ON public.live_matches;
CREATE POLICY "Members can clear an abandoned match" ON public.live_matches
    FOR DELETE TO authenticated
    USING (is_club_member(club_id) AND updated_at < now() - interval '3 hours');

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------

-- `players` is already published, which is all of check-in and queue.
ALTER PUBLICATION supabase_realtime ADD TABLE public.live_matches;
ALTER PUBLICATION supabase_realtime ADD TABLE public.club_tables;
