-- One row per human. `players` becomes purely the club membership.
--
-- Apply with `npm run db:sql sql/people.sql`, then `npm run db:dump` and
-- `npm run db:types`. See sql/README.md.
--
-- TAKE A BACKUP FIRST. This drops players.name, players.avatar_url and the four
-- denormalised name columns on games. None of that is recoverable from what is
-- left behind, and the backfill's name-matching merge is a judgement call that
-- cannot be undone once the source names are gone.
--
-- Why:
--
-- players.club_id was NOT NULL, so the row was the person *and* the membership.
-- One person in three clubs meant three rows, three ids, three copies of the
-- same name and the same face. The public directory at /players lists rows, so
-- that person appeared three times on three cards linking to three profiles.
--
-- Two places in the app already worked around it, which is the evidence the
-- model was wrong: AvatarUpload wrote one picture to every row matching user_id
-- ("one person, one face"), and getSession() did the same fan-out for the OAuth
-- picture on every single sign-in. Both collapse to a one-row update here.
--
-- The blocker was games. Four FKs pointed at players (club_id, name), so a
-- rename cascaded into game history and the name column could not move. But
-- games already carries player_1_id / player_2_id / player_1b_id / player_2b_id
-- and every piece of ranking maths (libs/dailyScore.ts, hooks/useEloRanking.ts)
-- reads the ids, never the names. The names were display-only denormalisation,
-- so they go, and the app resolves names through the id it already has.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. The table
-- ---------------------------------------------------------------------------

-- slug rather than a bare id in the public URL, matching clubs. slugify() and
-- the '-' || id collision suffix are the existing ones from sql/club-slug.sql;
-- there is no reserved-word list here because /players/:slug has no static
-- siblings to lose a match against.
--
-- No reserved unique index on name: two different people genuinely can share a
-- name, and the slug suffix is what keeps them apart. This is the constraint
-- players_club_name_ci_key used to enforce, dropped in step 5.
CREATE TABLE public.people (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text,
    name text NOT NULL,
    avatar_url text,
    user_id uuid UNIQUE REFERENCES auth.users (id),
    is_public boolean NOT NULL DEFAULT true,
    -- Dropped at the end of this file. It only exists so step 3 can map a
    -- players row back to the person the backfill folded it into.
    src_gkey text,
    CONSTRAINT people_name_check CHECK (char_length(btrim(name)) >= 1)
);

ALTER TABLE public.people ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 2. Backfill: which player rows are the same human
-- ---------------------------------------------------------------------------

-- The rule, in order of confidence:
--
--   1. Same user_id  -> same person. Proof, not a guess. Wins over everything,
--      including two different names ("Juan" in one club, "JC" in another).
--   2. An unlinked row whose name matches exactly one linked person -> that
--      person. The common case: an admin typed you onto a roster before you
--      signed up.
--   3. Unlinked rows sharing a name, none of them linked -> one person.
--   4. Unlinked rows sharing a name with *two or more different* user_ids ->
--      one person each. Two humans demonstrably share this name, so there is
--      nothing to attribute the unlinked row to. Left separate on purpose.
--
-- Rule 3 is the one that can be wrong: two different Juan Garcías in two clubs,
-- neither signed up, become one person. That was an explicit call — it is what
-- collapses the duplicate cards in the directory today. Read the groups before
-- committing:
--
--   SELECT gkey, array_agg(name ORDER BY id), array_agg(club_id ORDER BY id)
--   FROM ... GROUP BY gkey HAVING count(*) > 1;

CREATE TEMP TABLE grouped ON COMMIT DROP AS
WITH norm AS (
    SELECT
        id, club_id, name, avatar_url, user_id, is_public,
        lower(btrim(name)) AS nkey
    FROM public.players
),
-- Per name: how many distinct accounts claim it, and which one if there is
-- exactly one. count(DISTINCT ...) ignores NULLs, so unlinked rows do not vote.
--
-- array_agg()[1] rather than min(): there is no min()/max() aggregate for uuid
-- before Postgres 18, and this has to run on the version Supabase gives us.
by_name AS (
    SELECT
        nkey,
        count(DISTINCT user_id) AS uids,
        (array_agg(user_id) FILTER (WHERE user_id IS NOT NULL))[1] AS sole_uid
    FROM norm
    GROUP BY nkey
)
SELECT
    n.*,
    CASE
        WHEN n.user_id IS NOT NULL THEN 'u:' || n.user_id::text   -- rule 1
        WHEN b.uids = 1 THEN 'u:' || b.sole_uid::text             -- rule 2
        WHEN b.uids = 0 THEN 'n:' || n.nkey                       -- rule 3
        ELSE 'p:' || n.id::text                                   -- rule 4
    END AS gkey
FROM norm n
JOIN by_name b USING (nkey);

INSERT INTO public.people (src_gkey, name, avatar_url, user_id, is_public)
SELECT
    gkey,
    -- The linked row's spelling is the person's own; failing that, oldest wins.
    (array_agg(name ORDER BY (user_id IS NULL), id))[1],
    -- A data: URI is an upload the person chose. Anything else is the OAuth
    -- picture, which getSession() will put back on its own if it is still
    -- current. Prefer the choice.
    COALESCE(
        max(avatar_url) FILTER (WHERE avatar_url LIKE 'data:%'),
        max(avatar_url)
    ),
    (array_agg(user_id) FILTER (WHERE user_id IS NOT NULL))[1],
    -- Opting out in one club was the only way to opt out at all, so treat it as
    -- opting out entirely rather than silently re-listing them.
    bool_and(is_public)
FROM grouped
GROUP BY gkey;

-- Slugs need the id, so they land in a second pass. Same shape as the clubs
-- backfill in sql/club-slug.sql.
WITH ranked AS (
    SELECT
        id,
        public.slugify(name) AS base,
        row_number() OVER (PARTITION BY public.slugify(name) ORDER BY id) AS rn
    FROM public.people
)
UPDATE public.people p
SET slug = CASE WHEN r.rn > 1 THEN r.base || '-' || p.id ELSE r.base END
FROM ranked r
WHERE r.id = p.id;

ALTER TABLE public.people ALTER COLUMN slug SET NOT NULL;
CREATE UNIQUE INDEX people_slug_key ON public.people (slug);
ALTER TABLE public.people
    ADD CONSTRAINT people_slug_shape CHECK (slug ~ '^[a-z0-9][a-z0-9-]*$');

-- ---------------------------------------------------------------------------
-- 3. Wire players to people
-- ---------------------------------------------------------------------------

ALTER TABLE public.players ADD COLUMN person_id bigint;

UPDATE public.players pl
SET person_id = pe.id
FROM grouped g
JOIN public.people pe ON pe.src_gkey = g.gkey
WHERE pl.id = g.id;

ALTER TABLE public.players ALTER COLUMN person_id SET NOT NULL;
ALTER TABLE public.players
    ADD CONSTRAINT players_person_id_fkey
    FOREIGN KEY (person_id) REFERENCES public.people (id) ON DELETE CASCADE;

-- One membership per person per club. Replaces players_club_user_key, and says
-- the same thing about unlinked players that it could only say about linked
-- ones.
ALTER TABLE public.players
    ADD CONSTRAINT players_club_person_key UNIQUE (club_id, person_id);

CREATE INDEX players_person_idx ON public.players (person_id);

-- ---------------------------------------------------------------------------
-- 4. Games stop carrying names
-- ---------------------------------------------------------------------------

-- These four are the reason players.name could not move: ON UPDATE CASCADE from
-- players (club_id, name). The id columns beside them are not nullable for the
-- singles pair and already hold the same fact.
ALTER TABLE public.games DROP CONSTRAINT games_player_1_name_fkey;
ALTER TABLE public.games DROP CONSTRAINT games_player_2_name_fkey;
ALTER TABLE public.games DROP CONSTRAINT games_player_1b_name_fkey;
ALTER TABLE public.games DROP CONSTRAINT games_player_2b_name_fkey;

ALTER TABLE public.games DROP COLUMN player_1_name;
ALTER TABLE public.games DROP COLUMN player_2_name;
ALTER TABLE public.games DROP COLUMN player_1b_name;
ALTER TABLE public.games DROP COLUMN player_2b_name;

-- ---------------------------------------------------------------------------
-- 5. Strip the person out of players
-- ---------------------------------------------------------------------------

-- Both were the FK target for the columns just dropped, or a uniqueness rule
-- about a column that no longer lives here.
ALTER TABLE public.players DROP CONSTRAINT players_club_name_key;
ALTER TABLE public.players DROP CONSTRAINT players_club_user_key;
DROP INDEX public.players_club_name_ci_key;

-- Policies that read the columns about to disappear. Recreated in step 8.
DROP POLICY "Members can view club players" ON public.players;
DROP POLICY "Own row can be updated" ON public.players;
DROP POLICY "Players of public clubs are readable by anyone" ON public.players;

ALTER TABLE public.players DROP COLUMN name;
ALTER TABLE public.players DROP COLUMN avatar_url;
ALTER TABLE public.players DROP COLUMN user_id;
ALTER TABLE public.players DROP COLUMN is_public;

-- ---------------------------------------------------------------------------
-- 6. The auth surface
-- ---------------------------------------------------------------------------

-- Every one of these read players.user_id. They now hop through person_id. The
-- bodies are otherwise unchanged, so the ~15 policies that call them need no
-- edit at all — which is the whole reason this project put them in functions.

CREATE OR REPLACE FUNCTION public.is_own_player(pid integer)
    RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  SELECT EXISTS (
    SELECT 1 FROM players p
    JOIN people pe ON pe.id = p.person_id
    WHERE p.id = pid AND pe.user_id = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION public.is_club_member(cid integer)
    RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  SELECT EXISTS (
    SELECT 1 FROM players p
    JOIN people pe ON pe.id = p.person_id
    WHERE p.club_id = cid AND pe.user_id = auth.uid() AND p.status = 'active'
  );
$$;

-- Still the hardcoded seat: whoever holds players.id = 1 curates the shared
-- drill catalog. Only the hop to people changes.
CREATE OR REPLACE FUNCTION public.is_drill_admin()
    RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  SELECT EXISTS (
    SELECT 1 FROM players p
    JOIN people pe ON pe.id = p.person_id
    WHERE p.id = 1 AND pe.user_id = auth.uid()
  );
$$;

-- can_touch_player() and can_touch_plan() are unchanged: they resolve through
-- is_club_member(), which was just rewritten under them.

CREATE OR REPLACE FUNCTION public.club_preview(code text)
    RETURNS TABLE(club_id integer, club_name text, player_id integer, player_name text, claimable boolean)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  SELECT c.id, c.name, p.id, pe.name, pe.user_id IS NULL
  FROM clubs c
  LEFT JOIN players p ON p.club_id = c.id
  LEFT JOIN people pe ON pe.id = p.person_id
  WHERE c.join_code = lower(btrim(code))
  ORDER BY pe.name;
$$;

-- Joining a club is now two inserts, so the interesting part is what a *claim*
-- means. Claiming used to attach your account to one roster row. It now attaches
-- it to a person, and a person can hold memberships in clubs whose join code you
-- do not have — especially after this file's name-matching backfill.
--
-- So every one of that person's memberships drops to 'pending', not just the one
-- in the club you are joining. Holding one club's join code must not silently
-- make you an active member of another club, and the original trigger already
-- said as much about a single row: "holding the join code is not the same as
-- being that person".
--
-- The "name taken in this club" check is gone with the constraint behind it. Two
-- different people with the same name in one club is legal now; they are
-- distinct rows in people with distinct slugs and faces.
CREATE OR REPLACE FUNCTION public.join_club(code text, claim_player_id integer DEFAULT NULL, display_name text DEFAULT NULL)
    RETURNS integer
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
  cid INTEGER;
  uid UUID := auth.uid();
  me BIGINT;
  claimed BIGINT;
  pname TEXT;
BEGIN
  IF uid IS NULL THEN RAISE EXCEPTION 'sign in first'; END IF;

  SELECT id INTO cid FROM clubs WHERE join_code = lower(btrim(code));
  IF cid IS NULL THEN RAISE EXCEPTION 'unknown join code'; END IF;

  SELECT id INTO me FROM people WHERE user_id = uid;

  -- Already a member of this club, under whichever person is yours.
  IF me IS NOT NULL AND EXISTS (
    SELECT 1 FROM players WHERE club_id = cid AND person_id = me
  ) THEN
    RETURN cid;
  END IF;

  IF claim_player_id IS NOT NULL AND me IS NULL THEN
    UPDATE people pe
    SET user_id = uid
    FROM players p
    WHERE p.id = claim_player_id
      AND p.club_id = cid
      AND pe.id = p.person_id
      AND pe.user_id IS NULL
    RETURNING pe.id INTO claimed;

    IF claimed IS NOT NULL THEN
      UPDATE players SET status = 'pending' WHERE person_id = claimed;
      RETURN cid;
    END IF;
    -- Claimed between the preview and now, or you already had a person: fall
    -- through and join as somebody new.
  END IF;

  IF me IS NULL THEN
    pname := COALESCE(
      NULLIF(btrim(display_name), ''),
      NULLIF(btrim(auth.jwt() -> 'user_metadata' ->> 'full_name'), ''),
      'Player'
    );
    INSERT INTO people (name, user_id) VALUES (pname, uid) RETURNING id INTO me;
  END IF;

  INSERT INTO players (club_id, person_id, category, status)
  VALUES (cid, me, 3, 'pending');

  RETURN cid;
END $$;

-- Adding a guest — someone with no account, typed onto the roster by the club
-- owner — is two inserts across two tables, and the people insert cannot be
-- authorised by anything on the people row itself. So it is one function rather
-- than an RLS policy permissive enough to let any signed-in user create people
-- rows at will. useManagePlayers.createPlayer calls this.
CREATE OR REPLACE FUNCTION public.add_guest_player(cid integer, pname text, cat double precision DEFAULT 3)
    RETURNS bigint
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
  pid BIGINT;
  new_player BIGINT;
BEGIN
  IF NOT is_club_admin(cid) THEN
    RAISE EXCEPTION 'only the club owner may add players';
  END IF;
  IF btrim(COALESCE(pname, '')) = '' THEN
    RAISE EXCEPTION 'a player needs a name';
  END IF;

  -- Deliberately always a new person. Matching a guest onto an existing person
  -- by name is exactly the guess this file's backfill only made because it had
  -- no alternative; going forward, claiming is how two rows become one human.
  INSERT INTO people (name) VALUES (btrim(pname)) RETURNING id INTO pid;

  INSERT INTO players (club_id, person_id, category, status)
  VALUES (cid, pid, cat, 'active')
  RETURNING id INTO new_player;

  RETURN new_player;
END $$;

-- The old players_guard_user_id() guarded three things at once. user_id is not
-- on players any more, so it splits in two along the seam.

CREATE OR REPLACE FUNCTION public.people_guard_user_id()
    RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  -- No auth.uid() means service_role or the SQL editor: your own maintenance,
  -- including unlinking a person, still works.
  IF auth.uid() IS NULL THEN RETURN NEW; END IF;

  IF NEW.user_id IS DISTINCT FROM OLD.user_id THEN
    IF OLD.user_id IS NOT NULL OR NEW.user_id <> auth.uid() THEN
      RAISE EXCEPTION
        'people.user_id may only be set to your own id, and only on an unlinked person';
    END IF;
  END IF;

  -- The URL is written once and then never again, exactly as a club's is.
  NEW.slug := OLD.slug;

  RETURN NEW;
END $$;

CREATE TRIGGER people_guard_user_id
    BEFORE UPDATE ON public.people
    FOR EACH ROW
    EXECUTE FUNCTION public.people_guard_user_id();

CREATE OR REPLACE FUNCTION public.players_guard_membership()
    RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN NEW; END IF;

  IF NEW.club_id IS DISTINCT FROM OLD.club_id AND NOT is_club_admin(OLD.club_id) THEN
    RAISE EXCEPTION 'only the club owner may move a player between clubs';
  END IF;

  -- A membership never changes hands. Without this, "Members can update club
  -- players" — which exists so the roster editor can set a division — would also
  -- let a member point somebody else's membership at their own person.
  IF NEW.person_id IS DISTINCT FROM OLD.person_id THEN
    RAISE EXCEPTION 'a membership cannot be reassigned to another person';
  END IF;

  -- The one status change that is not the owner's: claiming an unclaimed person
  -- drops their memberships to 'pending'. join_club() relies on this.
  IF NEW.status IS DISTINCT FROM OLD.status
     AND NOT is_club_admin(OLD.club_id)
     AND NOT (
       NEW.status = 'pending'
       AND EXISTS (SELECT 1 FROM people WHERE id = NEW.person_id AND user_id = auth.uid())
     ) THEN
    RAISE EXCEPTION 'only the club owner may change a member''s status';
  END IF;

  RETURN NEW;
END $$;

DROP TRIGGER players_guard_user_id ON public.players;
DROP FUNCTION public.players_guard_user_id();

CREATE TRIGGER players_guard_membership
    BEFORE UPDATE ON public.players
    FOR EACH ROW
    EXECUTE FUNCTION public.players_guard_membership();

-- Deleting a membership must not delete the human — they may play elsewhere.
-- But a guest whose only membership just went is nothing but a dangling name, so
-- it goes with them. A person with an account is kept either way: they can sign
-- in tomorrow and join somewhere new, and their slug should survive that.
CREATE OR REPLACE FUNCTION public.people_drop_orphan()
    RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  DELETE FROM people
  WHERE id = OLD.person_id
    AND user_id IS NULL
    AND NOT EXISTS (SELECT 1 FROM players WHERE person_id = OLD.person_id);
  RETURN NULL;
END $$;

CREATE TRIGGER people_drop_orphan
    AFTER DELETE ON public.players
    FOR EACH ROW
    EXECUTE FUNCTION public.people_drop_orphan();

-- ---------------------------------------------------------------------------
-- 7. Slugs for people created from here on
-- ---------------------------------------------------------------------------

-- Mirrors clubs_set_slug() in sql/club-slug.sql, including the '-' || id
-- suffix. NEW.id is already populated in a BEFORE ROW trigger — column defaults
-- are applied first.
CREATE OR REPLACE FUNCTION public.people_set_slug()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    base text;
BEGIN
    IF NEW.slug IS NOT NULL AND NEW.slug <> '' THEN
        RETURN NEW;
    END IF;

    base := public.slugify(NEW.name);

    IF EXISTS (SELECT 1 FROM public.people WHERE slug = base AND id <> NEW.id) THEN
        NEW.slug := base || '-' || NEW.id;
    ELSE
        NEW.slug := base;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER people_set_slug
    BEFORE INSERT ON public.people
    FOR EACH ROW
    EXECUTE FUNCTION public.people_set_slug();

-- ---------------------------------------------------------------------------
-- 8. Policies
-- ---------------------------------------------------------------------------

-- players, rewritten without the columns that left. The three dropped in step 5
-- come back reading through people.

-- The second half is what a member with a *pending* membership needs to see
-- their own row: is_club_member() requires 'active'.
--
-- Written out rather than calling is_own_player(id), for the reason already
-- recorded in sql/public-pages.sql: that function takes an integer and
-- players.id is a bigint, so the call does not resolve. Inline is the better
-- answer regardless — person_id is on the row being tested, so this needs no
-- SECURITY DEFINER hop to reach it.
CREATE POLICY "Members can view club players" ON public.players
    FOR SELECT TO authenticated
    USING (
        public.is_club_member(club_id)
        OR person_id IN (SELECT id FROM public.people WHERE user_id = auth.uid())
    );

-- Same substitution, same reason.
CREATE POLICY "Own row can be updated" ON public.players
    FOR UPDATE TO authenticated
    USING (person_id IN (SELECT id FROM public.people WHERE user_id = auth.uid()))
    WITH CHECK (person_id IN (SELECT id FROM public.people WHERE user_id = auth.uid()));

-- is_public moved to people, so it is filtered there. A membership of a public
-- club stays readable either way: results and brackets have to be able to name
-- an unlisted player. Same reasoning as the note in sql/public-pages.sql.
CREATE POLICY "Players of public clubs are readable by anyone" ON public.players
    FOR SELECT TO anon
    USING (status = 'active' AND public.is_public_club(club_id));

-- The three predicates people's own policies need. Each one reads players, and
-- players' SELECT policy reads people — written inline that is a cycle, and
-- Postgres answers it with "infinite recursion detected in policy for relation".
-- SECURITY DEFINER breaks it: the function runs as the owner, for whom players'
-- RLS does not apply. Same device as is_club_member() and is_public_club(),
-- which already exist for the same class of problem.
CREATE OR REPLACE FUNCTION public.person_shares_club(pid bigint)
    RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  SELECT EXISTS (
    SELECT 1 FROM players p WHERE p.person_id = pid AND is_club_member(p.club_id)
  );
$$;

CREATE OR REPLACE FUNCTION public.person_is_admins_guest(pid bigint)
    RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  SELECT EXISTS (
    SELECT 1 FROM players p WHERE p.person_id = pid AND is_club_admin(p.club_id)
  );
$$;

CREATE OR REPLACE FUNCTION public.person_in_public_club(pid bigint)
    RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  SELECT EXISTS (
    SELECT 1 FROM players p
    WHERE p.person_id = pid AND p.status = 'active' AND is_public_club(p.club_id)
  );
$$;

-- people. Readable by anyone who shares a club with them, plus your own row
-- before any membership is active.
CREATE POLICY "Members can view people in their clubs" ON public.people
    FOR SELECT TO authenticated
    USING (user_id = auth.uid() OR public.person_shares_club(id));

-- Your name, your face, your listing. Nobody else's: the roster editor sets a
-- division, which is on players and stays there.
CREATE POLICY "Own person can be updated" ON public.people
    FOR UPDATE TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- A guest has no account, so nobody satisfies the policy above and their name
-- would be uneditable. The club that typed them in owns that name.
CREATE POLICY "Admin can update guests in their club" ON public.people
    FOR UPDATE TO authenticated
    USING (user_id IS NULL AND public.person_is_admins_guest(id))
    WITH CHECK (user_id IS NULL);

-- No INSERT or DELETE policy on purpose. join_club() and add_guest_player() are
-- SECURITY DEFINER and create people; people_drop_orphan() removes them. A
-- permissive insert policy would let any signed-in user fill the table.

-- is_public is not a condition here, for the reason publicPlayerQuery already
-- documents: it governs whether somebody is *listed*, and a name in a bracket
-- links to their profile. The directory filters it in the query instead.
CREATE POLICY "People of public clubs are readable by anyone" ON public.people
    FOR SELECT TO anon
    USING (public.person_in_public_club(id));

-- ---------------------------------------------------------------------------
-- 9. Grants
-- ---------------------------------------------------------------------------

GRANT ALL ON TABLE public.people TO authenticated;
GRANT ALL ON TABLE public.people TO service_role;
GRANT ALL ON SEQUENCE public.people_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.people_id_seq TO service_role;

-- Same column-grant approach as sql/public-pages.sql: a plain REVOKE SELECT plus
-- an explicit column list, so `select("*")` as anon fails loudly rather than
-- leaking a column added later. user_id is withheld — it is the auth user's id.
REVOKE SELECT ON public.people FROM anon;
GRANT SELECT (id, slug, name, avatar_url, is_public) ON public.people TO anon;

-- players.name, avatar_url and is_public took their column grants with them when
-- they were dropped; nothing to revoke. person_id is the new one anon needs, so
-- PostgREST can embed people from a players row.
GRANT SELECT (person_id) ON public.players TO anon;

GRANT EXECUTE ON FUNCTION public.add_guest_player(integer, text, double precision) TO authenticated;
GRANT EXECUTE ON FUNCTION public.add_guest_player(integer, text, double precision) TO service_role;

-- Called from inside policies, so every role that is subject to those policies
-- needs to be able to run them.
GRANT EXECUTE ON FUNCTION public.person_shares_club(bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.person_is_admins_guest(bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.person_in_public_club(bigint) TO anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 10. Tidy up
-- ---------------------------------------------------------------------------

ALTER TABLE public.people DROP COLUMN src_gkey;

-- Realtime: the app subscribes to people so a rename or a new avatar reaches
-- every other member's cache. Games and players are already on this publication.
ALTER PUBLICATION supabase_realtime ADD TABLE public.people;

COMMIT;

-- ponytail: no index on people.name for the public search, matching the note at
-- the end of sql/public-pages.sql. `name ilike '%q%'` cannot use a btree and
-- seq-scans; at these row counts that is still the cheaper answer. When it stops
-- being, pg_trgm and a GIN index here first — this is now the only table the
-- player search touches.
