-- Tournaments: double elimination, club leagues, and groups -> knockout.
--
-- Apply with `npm run db:sql sql/tournaments.sql`, then `npm run db:dump` and
-- `npm run db:types`. See sql/README.md — schema.sql is the source of truth,
-- this file is the change that produced it.
--
-- Shape notes:
--   * A match result is a normal `games` row, linked from tournament_matches.
--     Tournament play therefore lands in the club feed and both rankings with
--     no separate score model.
--   * Only round-1 knockout slots and league/group fixtures store p1_id/p2_id.
--     Who occupies a later slot is derived by walking winner_to/loser_to
--     (src/libs/bracket.ts), so recording a result is a single UPDATE and a
--     half-propagated bracket cannot exist.
--   * player id columns are `integer`, like challenges, so they can be passed
--     to is_own_player(integer) without a cast.

CREATE TABLE IF NOT EXISTS public.tournaments (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id     integer NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
    name        text NOT NULL,
    format      text NOT NULL,
    -- NULL = combined, every category. Mirrors players.category (1 strongest).
    category    smallint,
    -- Times each pair meets in a league or inside a group.
    legs        smallint NOT NULL DEFAULT 1,
    -- group_knockout only: how many players reach the bracket. The number of
    -- groups is advance / 2 — top two from each.
    advance     smallint,
    status      text NOT NULL DEFAULT 'open',
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT tournaments_name_check
        CHECK (char_length(btrim(name)) BETWEEN 1 AND 60),
    CONSTRAINT tournaments_format_check
        CHECK (format = ANY (ARRAY['double_elim', 'league', 'group_knockout'])),
    CONSTRAINT tournaments_category_check
        CHECK (category = ANY (ARRAY[1, 2, 3])),
    CONSTRAINT tournaments_legs_check CHECK (legs = ANY (ARRAY[1, 2])),
    CONSTRAINT tournaments_advance_values_check
        CHECK (advance = ANY (ARRAY[2, 4, 8, 16])),
    -- 'groups' is the gap between the group phase finishing and the bracket
    -- being cut, which needs the standings and so cannot happen at start.
    CONSTRAINT tournaments_status_check
        CHECK (status = ANY (ARRAY['open', 'groups', 'running', 'done'])),
    -- advance is required by exactly one format and meaningless to the others.
    CONSTRAINT tournaments_advance_check
        CHECK ((format = 'group_knockout') = (advance IS NOT NULL))
);


CREATE TABLE IF NOT EXISTS public.tournament_players (
    tournament_id integer NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
    player_id     integer NOT NULL REFERENCES public.players(id) ON DELETE CASCADE,
    created_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tournament_id, player_id)
);


CREATE TABLE IF NOT EXISTS public.tournament_matches (
    -- Client-generated, so a whole bracket's winner_to/loser_to pointers can be
    -- written in one insert.
    id             uuid PRIMARY KEY,
    tournament_id  integer NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
    bracket        text NOT NULL,
    -- Knockout round, or matchday within a league / group.
    round          smallint NOT NULL,
    slot           smallint NOT NULL,
    -- 1-based group number; NULL outside bracket = 'group'.
    group_no       smallint,
    p1_id          integer REFERENCES public.players(id) ON DELETE SET NULL,
    p2_id          integer REFERENCES public.players(id) ON DELETE SET NULL,
    -- Set directly on a bye, otherwise alongside game_id when a score is filed.
    winner_id      integer REFERENCES public.players(id) ON DELETE SET NULL,
    game_id        uuid REFERENCES public.games(id) ON DELETE SET NULL,
    winner_to      uuid REFERENCES public.tournament_matches(id) ON DELETE SET NULL,
    winner_to_slot smallint,
    loser_to       uuid REFERENCES public.tournament_matches(id) ON DELETE SET NULL,
    loser_to_slot  smallint,
    CONSTRAINT tournament_matches_bracket_check
        CHECK (bracket = ANY (ARRAY['group', 'winners', 'losers', 'final', 'league'])),
    CONSTRAINT tournament_matches_group_no_check
        CHECK ((bracket = 'group') = (group_no IS NOT NULL)),
    -- A result may only advance somebody who was actually in the match.
    CONSTRAINT tournament_matches_winner_check
        CHECK (winner_id IS NULL OR winner_id = p1_id OR winner_id = p2_id),
    CONSTRAINT tournament_matches_winner_slot_check
        CHECK (winner_to_slot = ANY (ARRAY[1, 2])),
    CONSTRAINT tournament_matches_loser_slot_check
        CHECK (loser_to_slot = ANY (ARRAY[1, 2])),
    -- NULLS NOT DISTINCT so the null group_no on knockout rows still collides,
    -- rather than letting duplicates through.
    CONSTRAINT tournament_matches_position_key
        UNIQUE NULLS NOT DISTINCT (tournament_id, bracket, group_no, round, slot)
);


CREATE INDEX IF NOT EXISTS tournaments_club_idx
    ON public.tournaments USING btree (club_id, status);

CREATE INDEX IF NOT EXISTS tournament_matches_t_idx
    ON public.tournament_matches USING btree (tournament_id, bracket, group_no, round, slot);


-- Which club a tournament belongs to. Lets the child tables reuse the existing
-- is_club_member / is_club_admin helpers without denormalising club_id.
-- Defined after the tables: a LANGUAGE sql body is parsed at creation, so it
-- cannot name `tournaments` before `tournaments` exists.
CREATE OR REPLACE FUNCTION public.tournament_club(tid integer) RETURNS integer
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
  SELECT club_id FROM tournaments WHERE id = tid;
$$;


ALTER TABLE public.tournaments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_matches ENABLE ROW LEVEL SECURITY;


-- tournaments: members read, the club owner runs them.
CREATE POLICY "Members can view club tournaments" ON public.tournaments
    FOR SELECT TO authenticated USING (public.is_club_member(club_id));

CREATE POLICY "Admin can create tournaments" ON public.tournaments
    FOR INSERT TO authenticated WITH CHECK (public.is_club_admin(club_id));

CREATE POLICY "Admin can update tournaments" ON public.tournaments
    FOR UPDATE TO authenticated USING (public.is_club_admin(club_id))
    WITH CHECK (public.is_club_admin(club_id));

CREATE POLICY "Admin can delete tournaments" ON public.tournaments
    FOR DELETE TO authenticated USING (public.is_club_admin(club_id));


-- tournament_players: you enter yourself, the admin can enter or remove anyone.
CREATE POLICY "Members can view entrants" ON public.tournament_players
    FOR SELECT TO authenticated
    USING (public.is_club_member(public.tournament_club(tournament_id)));

-- The entrant has to be a player OF THIS CLUB, not merely a player of yours.
-- Someone in two clubs has a player row in each, so is_own_player() alone would
-- let them enter their other club's player here — which then shows up nameless,
-- because the roster this club renders from does not contain it.
CREATE POLICY "Members can enter themselves" ON public.tournament_players
    FOR INSERT TO authenticated
    WITH CHECK (
      public.is_club_member(public.tournament_club(tournament_id))
      AND EXISTS (
        SELECT 1 FROM public.players
        WHERE players.id = tournament_players.player_id
          AND players.club_id = public.tournament_club(tournament_players.tournament_id)
      )
      AND (
        public.is_own_player(player_id)
        OR public.is_club_admin(public.tournament_club(tournament_id))
      )
    );

CREATE POLICY "Entrant or admin can withdraw" ON public.tournament_players
    FOR DELETE TO authenticated
    USING (
      public.is_own_player(player_id)
      OR public.is_club_admin(public.tournament_club(tournament_id))
    );


-- tournament_matches: the admin owns the structure, any member files a result.
CREATE POLICY "Members can view tournament matches" ON public.tournament_matches
    FOR SELECT TO authenticated
    USING (public.is_club_member(public.tournament_club(tournament_id)));

CREATE POLICY "Admin can generate matches" ON public.tournament_matches
    FOR INSERT TO authenticated
    WITH CHECK (public.is_club_admin(public.tournament_club(tournament_id)));

-- Postgres has no column-level RLS, so the policy opens the row and the trigger
-- below narrows it to the two columns a result actually consists of.
CREATE POLICY "Members can record results" ON public.tournament_matches
    FOR UPDATE TO authenticated
    USING (public.is_club_member(public.tournament_club(tournament_id)))
    WITH CHECK (public.is_club_member(public.tournament_club(tournament_id)));

CREATE POLICY "Admin can delete matches" ON public.tournament_matches
    FOR DELETE TO authenticated
    USING (public.is_club_admin(public.tournament_club(tournament_id)));


-- Filing a result is the one write a member has on a match, and it is exactly
-- two columns: which game it was, and who therefore goes through. The bracket's
-- shape — who is seeded where, and where a winner or loser is sent next — is the
-- organiser's, and rewriting it is how you would hand yourself a walkover.
--
-- This is a trigger rather than a policy because RLS is row-level: a policy can
-- say who may touch the row, not which columns of it they may touch.
CREATE OR REPLACE FUNCTION public.tournament_match_guard() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
BEGIN
  IF public.is_club_admin(public.tournament_club(NEW.tournament_id)) THEN
    RETURN NEW;
  END IF;

  IF ROW(NEW.id, NEW.tournament_id, NEW.bracket, NEW.round, NEW.slot,
         NEW.group_no, NEW.p1_id, NEW.p2_id,
         NEW.winner_to, NEW.winner_to_slot, NEW.loser_to, NEW.loser_to_slot)
     IS DISTINCT FROM
     ROW(OLD.id, OLD.tournament_id, OLD.bracket, OLD.round, OLD.slot,
         OLD.group_no, OLD.p1_id, OLD.p2_id,
         OLD.winner_to, OLD.winner_to_slot, OLD.loser_to, OLD.loser_to_slot)
  THEN
    RAISE EXCEPTION
      'only the club owner can change a match; members may set game_id and winner_id';
  END IF;

  -- p1_id and p2_id are only stored for the seats known at generation, so the
  -- column CHECK above says nothing about a semi-final. This is the part that
  -- still holds there: whoever goes through has to be in the tournament.
  IF NEW.winner_id IS NOT NULL AND NOT EXISTS (
       SELECT 1 FROM tournament_players
       WHERE tournament_id = NEW.tournament_id AND player_id = NEW.winner_id
     )
  THEN
    RAISE EXCEPTION 'the winner must be an entrant in this tournament';
  END IF;

  RETURN NEW;
END $$;


CREATE TRIGGER tournament_matches_guard
    BEFORE UPDATE ON public.tournament_matches
    FOR EACH ROW EXECUTE FUNCTION public.tournament_match_guard();


ALTER PUBLICATION supabase_realtime ADD TABLE ONLY public.tournaments;
ALTER PUBLICATION supabase_realtime ADD TABLE ONLY public.tournament_players;
ALTER PUBLICATION supabase_realtime ADD TABLE ONLY public.tournament_matches;
